// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: drivelist/v1/drivelist.proto

package drivelistv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	drivelistv1 "github.com/scottlaird/drivelist/internal/pb/drivelistv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CollectorName is the fully-qualified name of the Collector service.
	CollectorName = "drivelist.v1.Collector"
	// QueryName is the fully-qualified name of the Query service.
	QueryName = "drivelist.v1.Query"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CollectorReportInventoryProcedure is the fully-qualified name of the Collector's ReportInventory
	// RPC.
	CollectorReportInventoryProcedure = "/drivelist.v1.Collector/ReportInventory"
	// CollectorReportKernelProcedure is the fully-qualified name of the Collector's ReportKernel RPC.
	CollectorReportKernelProcedure = "/drivelist.v1.Collector/ReportKernel"
	// CollectorReportSmartProcedure is the fully-qualified name of the Collector's ReportSmart RPC.
	CollectorReportSmartProcedure = "/drivelist.v1.Collector/ReportSmart"
	// CollectorReportIOProcedure is the fully-qualified name of the Collector's ReportIO RPC.
	CollectorReportIOProcedure = "/drivelist.v1.Collector/ReportIO"
	// QueryListHostsProcedure is the fully-qualified name of the Query's ListHosts RPC.
	QueryListHostsProcedure = "/drivelist.v1.Query/ListHosts"
	// QueryListDrivesProcedure is the fully-qualified name of the Query's ListDrives RPC.
	QueryListDrivesProcedure = "/drivelist.v1.Query/ListDrives"
	// QueryGetDriveProcedure is the fully-qualified name of the Query's GetDrive RPC.
	QueryGetDriveProcedure = "/drivelist.v1.Query/GetDrive"
	// QueryGetDriveHistoryProcedure is the fully-qualified name of the Query's GetDriveHistory RPC.
	QueryGetDriveHistoryProcedure = "/drivelist.v1.Query/GetDriveHistory"
	// QueryListEventsProcedure is the fully-qualified name of the Query's ListEvents RPC.
	QueryListEventsProcedure = "/drivelist.v1.Query/ListEvents"
	// QueryListMissingProcedure is the fully-qualified name of the Query's ListMissing RPC.
	QueryListMissingProcedure = "/drivelist.v1.Query/ListMissing"
	// QueryAnnotateProcedure is the fully-qualified name of the Query's Annotate RPC.
	QueryAnnotateProcedure = "/drivelist.v1.Query/Annotate"
	// QueryGetKernelProcedure is the fully-qualified name of the Query's GetKernel RPC.
	QueryGetKernelProcedure = "/drivelist.v1.Query/GetKernel"
	// QueryGetSmartProcedure is the fully-qualified name of the Query's GetSmart RPC.
	QueryGetSmartProcedure = "/drivelist.v1.Query/GetSmart"
	// QueryGetIOProcedure is the fully-qualified name of the Query's GetIO RPC.
	QueryGetIOProcedure = "/drivelist.v1.Query/GetIO"
	// QueryCompareIOProcedure is the fully-qualified name of the Query's CompareIO RPC.
	QueryCompareIOProcedure = "/drivelist.v1.Query/CompareIO"
	// QueryMergeDrivesProcedure is the fully-qualified name of the Query's MergeDrives RPC.
	QueryMergeDrivesProcedure = "/drivelist.v1.Query/MergeDrives"
	// QueryMergeHostsProcedure is the fully-qualified name of the Query's MergeHosts RPC.
	QueryMergeHostsProcedure = "/drivelist.v1.Query/MergeHosts"
	// QueryRebuildProcedure is the fully-qualified name of the Query's Rebuild RPC.
	QueryRebuildProcedure = "/drivelist.v1.Query/Rebuild"
	// QueryListEnclosuresProcedure is the fully-qualified name of the Query's ListEnclosures RPC.
	QueryListEnclosuresProcedure = "/drivelist.v1.Query/ListEnclosures"
	// QueryNameEnclosureProcedure is the fully-qualified name of the Query's NameEnclosure RPC.
	QueryNameEnclosureProcedure = "/drivelist.v1.Query/NameEnclosure"
	// QueryGetSASProcedure is the fully-qualified name of the Query's GetSAS RPC.
	QueryGetSASProcedure = "/drivelist.v1.Query/GetSAS"
	// QueryListSASErrorsProcedure is the fully-qualified name of the Query's ListSASErrors RPC.
	QueryListSASErrorsProcedure = "/drivelist.v1.Query/ListSASErrors"
)

// CollectorClient is a client for the drivelist.v1.Collector service.
type CollectorClient interface {
	// ReportInventory posts the complete current inventory of one host.
	ReportInventory(context.Context, *connect.Request[drivelistv1.ReportInventoryRequest]) (*connect.Response[drivelistv1.ReportInventoryResponse], error)
	// ReportKernel posts hourly counts of classified kernel log lines per
	// drive. Each bucket is sent once, complete; resending replaces.
	ReportKernel(context.Context, *connect.Request[drivelistv1.ReportKernelRequest]) (*connect.Response[drivelistv1.ReportAck], error)
	// ReportSmart posts SMART summaries, with the raw smartctl JSON at most
	// daily per drive or when the summary changed.
	ReportSmart(context.Context, *connect.Request[drivelistv1.ReportSmartRequest]) (*connect.Response[drivelistv1.ReportAck], error)
	// ReportIO posts hourly I/O buckets per drive, as deltas of the kernel's
	// counters. A bucket already stored is replaced.
	ReportIO(context.Context, *connect.Request[drivelistv1.ReportIORequest]) (*connect.Response[drivelistv1.ReportAck], error)
}

// NewCollectorClient constructs a client for the drivelist.v1.Collector service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCollectorClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CollectorClient {
	baseURL = strings.TrimRight(baseURL, "/")
	collectorMethods := drivelistv1.File_drivelist_v1_drivelist_proto.Services().ByName("Collector").Methods()
	return &collectorClient{
		reportInventory: connect.NewClient[drivelistv1.ReportInventoryRequest, drivelistv1.ReportInventoryResponse](
			httpClient,
			baseURL+CollectorReportInventoryProcedure,
			connect.WithSchema(collectorMethods.ByName("ReportInventory")),
			connect.WithClientOptions(opts...),
		),
		reportKernel: connect.NewClient[drivelistv1.ReportKernelRequest, drivelistv1.ReportAck](
			httpClient,
			baseURL+CollectorReportKernelProcedure,
			connect.WithSchema(collectorMethods.ByName("ReportKernel")),
			connect.WithClientOptions(opts...),
		),
		reportSmart: connect.NewClient[drivelistv1.ReportSmartRequest, drivelistv1.ReportAck](
			httpClient,
			baseURL+CollectorReportSmartProcedure,
			connect.WithSchema(collectorMethods.ByName("ReportSmart")),
			connect.WithClientOptions(opts...),
		),
		reportIO: connect.NewClient[drivelistv1.ReportIORequest, drivelistv1.ReportAck](
			httpClient,
			baseURL+CollectorReportIOProcedure,
			connect.WithSchema(collectorMethods.ByName("ReportIO")),
			connect.WithClientOptions(opts...),
		),
	}
}

// collectorClient implements CollectorClient.
type collectorClient struct {
	reportInventory *connect.Client[drivelistv1.ReportInventoryRequest, drivelistv1.ReportInventoryResponse]
	reportKernel    *connect.Client[drivelistv1.ReportKernelRequest, drivelistv1.ReportAck]
	reportSmart     *connect.Client[drivelistv1.ReportSmartRequest, drivelistv1.ReportAck]
	reportIO        *connect.Client[drivelistv1.ReportIORequest, drivelistv1.ReportAck]
}

// ReportInventory calls drivelist.v1.Collector.ReportInventory.
func (c *collectorClient) ReportInventory(ctx context.Context, req *connect.Request[drivelistv1.ReportInventoryRequest]) (*connect.Response[drivelistv1.ReportInventoryResponse], error) {
	return c.reportInventory.CallUnary(ctx, req)
}

// ReportKernel calls drivelist.v1.Collector.ReportKernel.
func (c *collectorClient) ReportKernel(ctx context.Context, req *connect.Request[drivelistv1.ReportKernelRequest]) (*connect.Response[drivelistv1.ReportAck], error) {
	return c.reportKernel.CallUnary(ctx, req)
}

// ReportSmart calls drivelist.v1.Collector.ReportSmart.
func (c *collectorClient) ReportSmart(ctx context.Context, req *connect.Request[drivelistv1.ReportSmartRequest]) (*connect.Response[drivelistv1.ReportAck], error) {
	return c.reportSmart.CallUnary(ctx, req)
}

// ReportIO calls drivelist.v1.Collector.ReportIO.
func (c *collectorClient) ReportIO(ctx context.Context, req *connect.Request[drivelistv1.ReportIORequest]) (*connect.Response[drivelistv1.ReportAck], error) {
	return c.reportIO.CallUnary(ctx, req)
}

// CollectorHandler is an implementation of the drivelist.v1.Collector service.
type CollectorHandler interface {
	// ReportInventory posts the complete current inventory of one host.
	ReportInventory(context.Context, *connect.Request[drivelistv1.ReportInventoryRequest]) (*connect.Response[drivelistv1.ReportInventoryResponse], error)
	// ReportKernel posts hourly counts of classified kernel log lines per
	// drive. Each bucket is sent once, complete; resending replaces.
	ReportKernel(context.Context, *connect.Request[drivelistv1.ReportKernelRequest]) (*connect.Response[drivelistv1.ReportAck], error)
	// ReportSmart posts SMART summaries, with the raw smartctl JSON at most
	// daily per drive or when the summary changed.
	ReportSmart(context.Context, *connect.Request[drivelistv1.ReportSmartRequest]) (*connect.Response[drivelistv1.ReportAck], error)
	// ReportIO posts hourly I/O buckets per drive, as deltas of the kernel's
	// counters. A bucket already stored is replaced.
	ReportIO(context.Context, *connect.Request[drivelistv1.ReportIORequest]) (*connect.Response[drivelistv1.ReportAck], error)
}

// NewCollectorHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCollectorHandler(svc CollectorHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	collectorMethods := drivelistv1.File_drivelist_v1_drivelist_proto.Services().ByName("Collector").Methods()
	collectorReportInventoryHandler := connect.NewUnaryHandler(
		CollectorReportInventoryProcedure,
		svc.ReportInventory,
		connect.WithSchema(collectorMethods.ByName("ReportInventory")),
		connect.WithHandlerOptions(opts...),
	)
	collectorReportKernelHandler := connect.NewUnaryHandler(
		CollectorReportKernelProcedure,
		svc.ReportKernel,
		connect.WithSchema(collectorMethods.ByName("ReportKernel")),
		connect.WithHandlerOptions(opts...),
	)
	collectorReportSmartHandler := connect.NewUnaryHandler(
		CollectorReportSmartProcedure,
		svc.ReportSmart,
		connect.WithSchema(collectorMethods.ByName("ReportSmart")),
		connect.WithHandlerOptions(opts...),
	)
	collectorReportIOHandler := connect.NewUnaryHandler(
		CollectorReportIOProcedure,
		svc.ReportIO,
		connect.WithSchema(collectorMethods.ByName("ReportIO")),
		connect.WithHandlerOptions(opts...),
	)
	return "/drivelist.v1.Collector/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CollectorReportInventoryProcedure:
			collectorReportInventoryHandler.ServeHTTP(w, r)
		case CollectorReportKernelProcedure:
			collectorReportKernelHandler.ServeHTTP(w, r)
		case CollectorReportSmartProcedure:
			collectorReportSmartHandler.ServeHTTP(w, r)
		case CollectorReportIOProcedure:
			collectorReportIOHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCollectorHandler returns CodeUnimplemented from all methods.
type UnimplementedCollectorHandler struct{}

func (UnimplementedCollectorHandler) ReportInventory(context.Context, *connect.Request[drivelistv1.ReportInventoryRequest]) (*connect.Response[drivelistv1.ReportInventoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Collector.ReportInventory is not implemented"))
}

func (UnimplementedCollectorHandler) ReportKernel(context.Context, *connect.Request[drivelistv1.ReportKernelRequest]) (*connect.Response[drivelistv1.ReportAck], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Collector.ReportKernel is not implemented"))
}

func (UnimplementedCollectorHandler) ReportSmart(context.Context, *connect.Request[drivelistv1.ReportSmartRequest]) (*connect.Response[drivelistv1.ReportAck], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Collector.ReportSmart is not implemented"))
}

func (UnimplementedCollectorHandler) ReportIO(context.Context, *connect.Request[drivelistv1.ReportIORequest]) (*connect.Response[drivelistv1.ReportAck], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Collector.ReportIO is not implemented"))
}

// QueryClient is a client for the drivelist.v1.Query service.
type QueryClient interface {
	ListHosts(context.Context, *connect.Request[drivelistv1.ListHostsRequest]) (*connect.Response[drivelistv1.ListHostsResponse], error)
	ListDrives(context.Context, *connect.Request[drivelistv1.ListDrivesRequest]) (*connect.Response[drivelistv1.ListDrivesResponse], error)
	// GetDrive resolves a serial, WWN, or unambiguous prefix of either.
	GetDrive(context.Context, *connect.Request[drivelistv1.GetDriveRequest]) (*connect.Response[drivelistv1.GetDriveResponse], error)
	// GetDriveHistory returns every placement and event for one drive,
	// oldest first.
	GetDriveHistory(context.Context, *connect.Request[drivelistv1.GetDriveHistoryRequest]) (*connect.Response[drivelistv1.GetDriveHistoryResponse], error)
	ListEvents(context.Context, *connect.Request[drivelistv1.ListEventsRequest]) (*connect.Response[drivelistv1.ListEventsResponse], error)
	// ListMissing returns drives whose last placement ended with vanished and
	// whose status does not expect absence, plus open pool ghosts.
	ListMissing(context.Context, *connect.Request[drivelistv1.ListMissingRequest]) (*connect.Response[drivelistv1.ListMissingResponse], error)
	// Annotate records a manual status change or note as an event.
	Annotate(context.Context, *connect.Request[drivelistv1.AnnotateRequest]) (*connect.Response[drivelistv1.AnnotateResponse], error)
	// GetKernel returns a drive's kernel log counts, newest bucket first.
	GetKernel(context.Context, *connect.Request[drivelistv1.GetKernelRequest]) (*connect.Response[drivelistv1.GetKernelResponse], error)
	// GetSmart returns a drive's SMART samples, newest first, optionally with
	// the latest raw smartctl output.
	GetSmart(context.Context, *connect.Request[drivelistv1.GetSmartRequest]) (*connect.Response[drivelistv1.GetSmartResponse], error)
	// GetIO returns a drive's I/O buckets, newest first.
	GetIO(context.Context, *connect.Request[drivelistv1.GetIORequest]) (*connect.Response[drivelistv1.GetIOResponse], error)
	// CompareIO returns every currently placed drive's latency and
	// utilisation over a window next to the median of its vdev, so an
	// outlier among identical drives stands out.
	CompareIO(context.Context, *connect.Request[drivelistv1.CompareIORequest]) (*connect.Response[drivelistv1.CompareIOResponse], error)
	// MergeDrives folds one drive record into another: use it when one
	// physical drive got two records, such as from being seen once without
	// its WWN. Everything moves to `into`; `from` keeps resolving to it.
	MergeDrives(context.Context, *connect.Request[drivelistv1.MergeDrivesRequest]) (*connect.Response[drivelistv1.MergeDrivesResponse], error)
	// MergeHosts folds one host record into another, for a host reinstalled
	// with a new machine id. Refs are hostnames or machine ids.
	MergeHosts(context.Context, *connect.Request[drivelistv1.MergeHostsRequest]) (*connect.Response[drivelistv1.MergeHostsResponse], error)
	// Rebuild recomputes every placement and derived event from the stored
	// snapshots. Annotations, merges, samples and ghosts are kept.
	Rebuild(context.Context, *connect.Request[drivelistv1.RebuildRequest]) (*connect.Response[drivelistv1.RebuildResponse], error)
	// ListEnclosures lists the enclosures drives sit in.
	ListEnclosures(context.Context, *connect.Request[drivelistv1.ListEnclosuresRequest]) (*connect.Response[drivelistv1.ListEnclosuresResponse], error)
	// NameEnclosure records what a person calls an enclosure; every view
	// shows the name in place of the kernel's expander-H:N from then on.
	NameEnclosure(context.Context, *connect.Request[drivelistv1.NameEnclosureRequest]) (*connect.Response[drivelistv1.NameEnclosureResponse], error)
	// GetSAS returns one host's SAS topology as the server last saw it.
	GetSAS(context.Context, *connect.Request[drivelistv1.GetSASRequest]) (*connect.Response[drivelistv1.GetSASResponse], error)
	// ListSASErrors lists the phys whose error counters climbed in a window.
	ListSASErrors(context.Context, *connect.Request[drivelistv1.ListSASErrorsRequest]) (*connect.Response[drivelistv1.ListSASErrorsResponse], error)
}

// NewQueryClient constructs a client for the drivelist.v1.Query service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewQueryClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) QueryClient {
	baseURL = strings.TrimRight(baseURL, "/")
	queryMethods := drivelistv1.File_drivelist_v1_drivelist_proto.Services().ByName("Query").Methods()
	return &queryClient{
		listHosts: connect.NewClient[drivelistv1.ListHostsRequest, drivelistv1.ListHostsResponse](
			httpClient,
			baseURL+QueryListHostsProcedure,
			connect.WithSchema(queryMethods.ByName("ListHosts")),
			connect.WithClientOptions(opts...),
		),
		listDrives: connect.NewClient[drivelistv1.ListDrivesRequest, drivelistv1.ListDrivesResponse](
			httpClient,
			baseURL+QueryListDrivesProcedure,
			connect.WithSchema(queryMethods.ByName("ListDrives")),
			connect.WithClientOptions(opts...),
		),
		getDrive: connect.NewClient[drivelistv1.GetDriveRequest, drivelistv1.GetDriveResponse](
			httpClient,
			baseURL+QueryGetDriveProcedure,
			connect.WithSchema(queryMethods.ByName("GetDrive")),
			connect.WithClientOptions(opts...),
		),
		getDriveHistory: connect.NewClient[drivelistv1.GetDriveHistoryRequest, drivelistv1.GetDriveHistoryResponse](
			httpClient,
			baseURL+QueryGetDriveHistoryProcedure,
			connect.WithSchema(queryMethods.ByName("GetDriveHistory")),
			connect.WithClientOptions(opts...),
		),
		listEvents: connect.NewClient[drivelistv1.ListEventsRequest, drivelistv1.ListEventsResponse](
			httpClient,
			baseURL+QueryListEventsProcedure,
			connect.WithSchema(queryMethods.ByName("ListEvents")),
			connect.WithClientOptions(opts...),
		),
		listMissing: connect.NewClient[drivelistv1.ListMissingRequest, drivelistv1.ListMissingResponse](
			httpClient,
			baseURL+QueryListMissingProcedure,
			connect.WithSchema(queryMethods.ByName("ListMissing")),
			connect.WithClientOptions(opts...),
		),
		annotate: connect.NewClient[drivelistv1.AnnotateRequest, drivelistv1.AnnotateResponse](
			httpClient,
			baseURL+QueryAnnotateProcedure,
			connect.WithSchema(queryMethods.ByName("Annotate")),
			connect.WithClientOptions(opts...),
		),
		getKernel: connect.NewClient[drivelistv1.GetKernelRequest, drivelistv1.GetKernelResponse](
			httpClient,
			baseURL+QueryGetKernelProcedure,
			connect.WithSchema(queryMethods.ByName("GetKernel")),
			connect.WithClientOptions(opts...),
		),
		getSmart: connect.NewClient[drivelistv1.GetSmartRequest, drivelistv1.GetSmartResponse](
			httpClient,
			baseURL+QueryGetSmartProcedure,
			connect.WithSchema(queryMethods.ByName("GetSmart")),
			connect.WithClientOptions(opts...),
		),
		getIO: connect.NewClient[drivelistv1.GetIORequest, drivelistv1.GetIOResponse](
			httpClient,
			baseURL+QueryGetIOProcedure,
			connect.WithSchema(queryMethods.ByName("GetIO")),
			connect.WithClientOptions(opts...),
		),
		compareIO: connect.NewClient[drivelistv1.CompareIORequest, drivelistv1.CompareIOResponse](
			httpClient,
			baseURL+QueryCompareIOProcedure,
			connect.WithSchema(queryMethods.ByName("CompareIO")),
			connect.WithClientOptions(opts...),
		),
		mergeDrives: connect.NewClient[drivelistv1.MergeDrivesRequest, drivelistv1.MergeDrivesResponse](
			httpClient,
			baseURL+QueryMergeDrivesProcedure,
			connect.WithSchema(queryMethods.ByName("MergeDrives")),
			connect.WithClientOptions(opts...),
		),
		mergeHosts: connect.NewClient[drivelistv1.MergeHostsRequest, drivelistv1.MergeHostsResponse](
			httpClient,
			baseURL+QueryMergeHostsProcedure,
			connect.WithSchema(queryMethods.ByName("MergeHosts")),
			connect.WithClientOptions(opts...),
		),
		rebuild: connect.NewClient[drivelistv1.RebuildRequest, drivelistv1.RebuildResponse](
			httpClient,
			baseURL+QueryRebuildProcedure,
			connect.WithSchema(queryMethods.ByName("Rebuild")),
			connect.WithClientOptions(opts...),
		),
		listEnclosures: connect.NewClient[drivelistv1.ListEnclosuresRequest, drivelistv1.ListEnclosuresResponse](
			httpClient,
			baseURL+QueryListEnclosuresProcedure,
			connect.WithSchema(queryMethods.ByName("ListEnclosures")),
			connect.WithClientOptions(opts...),
		),
		nameEnclosure: connect.NewClient[drivelistv1.NameEnclosureRequest, drivelistv1.NameEnclosureResponse](
			httpClient,
			baseURL+QueryNameEnclosureProcedure,
			connect.WithSchema(queryMethods.ByName("NameEnclosure")),
			connect.WithClientOptions(opts...),
		),
		getSAS: connect.NewClient[drivelistv1.GetSASRequest, drivelistv1.GetSASResponse](
			httpClient,
			baseURL+QueryGetSASProcedure,
			connect.WithSchema(queryMethods.ByName("GetSAS")),
			connect.WithClientOptions(opts...),
		),
		listSASErrors: connect.NewClient[drivelistv1.ListSASErrorsRequest, drivelistv1.ListSASErrorsResponse](
			httpClient,
			baseURL+QueryListSASErrorsProcedure,
			connect.WithSchema(queryMethods.ByName("ListSASErrors")),
			connect.WithClientOptions(opts...),
		),
	}
}

// queryClient implements QueryClient.
type queryClient struct {
	listHosts       *connect.Client[drivelistv1.ListHostsRequest, drivelistv1.ListHostsResponse]
	listDrives      *connect.Client[drivelistv1.ListDrivesRequest, drivelistv1.ListDrivesResponse]
	getDrive        *connect.Client[drivelistv1.GetDriveRequest, drivelistv1.GetDriveResponse]
	getDriveHistory *connect.Client[drivelistv1.GetDriveHistoryRequest, drivelistv1.GetDriveHistoryResponse]
	listEvents      *connect.Client[drivelistv1.ListEventsRequest, drivelistv1.ListEventsResponse]
	listMissing     *connect.Client[drivelistv1.ListMissingRequest, drivelistv1.ListMissingResponse]
	annotate        *connect.Client[drivelistv1.AnnotateRequest, drivelistv1.AnnotateResponse]
	getKernel       *connect.Client[drivelistv1.GetKernelRequest, drivelistv1.GetKernelResponse]
	getSmart        *connect.Client[drivelistv1.GetSmartRequest, drivelistv1.GetSmartResponse]
	getIO           *connect.Client[drivelistv1.GetIORequest, drivelistv1.GetIOResponse]
	compareIO       *connect.Client[drivelistv1.CompareIORequest, drivelistv1.CompareIOResponse]
	mergeDrives     *connect.Client[drivelistv1.MergeDrivesRequest, drivelistv1.MergeDrivesResponse]
	mergeHosts      *connect.Client[drivelistv1.MergeHostsRequest, drivelistv1.MergeHostsResponse]
	rebuild         *connect.Client[drivelistv1.RebuildRequest, drivelistv1.RebuildResponse]
	listEnclosures  *connect.Client[drivelistv1.ListEnclosuresRequest, drivelistv1.ListEnclosuresResponse]
	nameEnclosure   *connect.Client[drivelistv1.NameEnclosureRequest, drivelistv1.NameEnclosureResponse]
	getSAS          *connect.Client[drivelistv1.GetSASRequest, drivelistv1.GetSASResponse]
	listSASErrors   *connect.Client[drivelistv1.ListSASErrorsRequest, drivelistv1.ListSASErrorsResponse]
}

// ListHosts calls drivelist.v1.Query.ListHosts.
func (c *queryClient) ListHosts(ctx context.Context, req *connect.Request[drivelistv1.ListHostsRequest]) (*connect.Response[drivelistv1.ListHostsResponse], error) {
	return c.listHosts.CallUnary(ctx, req)
}

// ListDrives calls drivelist.v1.Query.ListDrives.
func (c *queryClient) ListDrives(ctx context.Context, req *connect.Request[drivelistv1.ListDrivesRequest]) (*connect.Response[drivelistv1.ListDrivesResponse], error) {
	return c.listDrives.CallUnary(ctx, req)
}

// GetDrive calls drivelist.v1.Query.GetDrive.
func (c *queryClient) GetDrive(ctx context.Context, req *connect.Request[drivelistv1.GetDriveRequest]) (*connect.Response[drivelistv1.GetDriveResponse], error) {
	return c.getDrive.CallUnary(ctx, req)
}

// GetDriveHistory calls drivelist.v1.Query.GetDriveHistory.
func (c *queryClient) GetDriveHistory(ctx context.Context, req *connect.Request[drivelistv1.GetDriveHistoryRequest]) (*connect.Response[drivelistv1.GetDriveHistoryResponse], error) {
	return c.getDriveHistory.CallUnary(ctx, req)
}

// ListEvents calls drivelist.v1.Query.ListEvents.
func (c *queryClient) ListEvents(ctx context.Context, req *connect.Request[drivelistv1.ListEventsRequest]) (*connect.Response[drivelistv1.ListEventsResponse], error) {
	return c.listEvents.CallUnary(ctx, req)
}

// ListMissing calls drivelist.v1.Query.ListMissing.
func (c *queryClient) ListMissing(ctx context.Context, req *connect.Request[drivelistv1.ListMissingRequest]) (*connect.Response[drivelistv1.ListMissingResponse], error) {
	return c.listMissing.CallUnary(ctx, req)
}

// Annotate calls drivelist.v1.Query.Annotate.
func (c *queryClient) Annotate(ctx context.Context, req *connect.Request[drivelistv1.AnnotateRequest]) (*connect.Response[drivelistv1.AnnotateResponse], error) {
	return c.annotate.CallUnary(ctx, req)
}

// GetKernel calls drivelist.v1.Query.GetKernel.
func (c *queryClient) GetKernel(ctx context.Context, req *connect.Request[drivelistv1.GetKernelRequest]) (*connect.Response[drivelistv1.GetKernelResponse], error) {
	return c.getKernel.CallUnary(ctx, req)
}

// GetSmart calls drivelist.v1.Query.GetSmart.
func (c *queryClient) GetSmart(ctx context.Context, req *connect.Request[drivelistv1.GetSmartRequest]) (*connect.Response[drivelistv1.GetSmartResponse], error) {
	return c.getSmart.CallUnary(ctx, req)
}

// GetIO calls drivelist.v1.Query.GetIO.
func (c *queryClient) GetIO(ctx context.Context, req *connect.Request[drivelistv1.GetIORequest]) (*connect.Response[drivelistv1.GetIOResponse], error) {
	return c.getIO.CallUnary(ctx, req)
}

// CompareIO calls drivelist.v1.Query.CompareIO.
func (c *queryClient) CompareIO(ctx context.Context, req *connect.Request[drivelistv1.CompareIORequest]) (*connect.Response[drivelistv1.CompareIOResponse], error) {
	return c.compareIO.CallUnary(ctx, req)
}

// MergeDrives calls drivelist.v1.Query.MergeDrives.
func (c *queryClient) MergeDrives(ctx context.Context, req *connect.Request[drivelistv1.MergeDrivesRequest]) (*connect.Response[drivelistv1.MergeDrivesResponse], error) {
	return c.mergeDrives.CallUnary(ctx, req)
}

// MergeHosts calls drivelist.v1.Query.MergeHosts.
func (c *queryClient) MergeHosts(ctx context.Context, req *connect.Request[drivelistv1.MergeHostsRequest]) (*connect.Response[drivelistv1.MergeHostsResponse], error) {
	return c.mergeHosts.CallUnary(ctx, req)
}

// Rebuild calls drivelist.v1.Query.Rebuild.
func (c *queryClient) Rebuild(ctx context.Context, req *connect.Request[drivelistv1.RebuildRequest]) (*connect.Response[drivelistv1.RebuildResponse], error) {
	return c.rebuild.CallUnary(ctx, req)
}

// ListEnclosures calls drivelist.v1.Query.ListEnclosures.
func (c *queryClient) ListEnclosures(ctx context.Context, req *connect.Request[drivelistv1.ListEnclosuresRequest]) (*connect.Response[drivelistv1.ListEnclosuresResponse], error) {
	return c.listEnclosures.CallUnary(ctx, req)
}

// NameEnclosure calls drivelist.v1.Query.NameEnclosure.
func (c *queryClient) NameEnclosure(ctx context.Context, req *connect.Request[drivelistv1.NameEnclosureRequest]) (*connect.Response[drivelistv1.NameEnclosureResponse], error) {
	return c.nameEnclosure.CallUnary(ctx, req)
}

// GetSAS calls drivelist.v1.Query.GetSAS.
func (c *queryClient) GetSAS(ctx context.Context, req *connect.Request[drivelistv1.GetSASRequest]) (*connect.Response[drivelistv1.GetSASResponse], error) {
	return c.getSAS.CallUnary(ctx, req)
}

// ListSASErrors calls drivelist.v1.Query.ListSASErrors.
func (c *queryClient) ListSASErrors(ctx context.Context, req *connect.Request[drivelistv1.ListSASErrorsRequest]) (*connect.Response[drivelistv1.ListSASErrorsResponse], error) {
	return c.listSASErrors.CallUnary(ctx, req)
}

// QueryHandler is an implementation of the drivelist.v1.Query service.
type QueryHandler interface {
	ListHosts(context.Context, *connect.Request[drivelistv1.ListHostsRequest]) (*connect.Response[drivelistv1.ListHostsResponse], error)
	ListDrives(context.Context, *connect.Request[drivelistv1.ListDrivesRequest]) (*connect.Response[drivelistv1.ListDrivesResponse], error)
	// GetDrive resolves a serial, WWN, or unambiguous prefix of either.
	GetDrive(context.Context, *connect.Request[drivelistv1.GetDriveRequest]) (*connect.Response[drivelistv1.GetDriveResponse], error)
	// GetDriveHistory returns every placement and event for one drive,
	// oldest first.
	GetDriveHistory(context.Context, *connect.Request[drivelistv1.GetDriveHistoryRequest]) (*connect.Response[drivelistv1.GetDriveHistoryResponse], error)
	ListEvents(context.Context, *connect.Request[drivelistv1.ListEventsRequest]) (*connect.Response[drivelistv1.ListEventsResponse], error)
	// ListMissing returns drives whose last placement ended with vanished and
	// whose status does not expect absence, plus open pool ghosts.
	ListMissing(context.Context, *connect.Request[drivelistv1.ListMissingRequest]) (*connect.Response[drivelistv1.ListMissingResponse], error)
	// Annotate records a manual status change or note as an event.
	Annotate(context.Context, *connect.Request[drivelistv1.AnnotateRequest]) (*connect.Response[drivelistv1.AnnotateResponse], error)
	// GetKernel returns a drive's kernel log counts, newest bucket first.
	GetKernel(context.Context, *connect.Request[drivelistv1.GetKernelRequest]) (*connect.Response[drivelistv1.GetKernelResponse], error)
	// GetSmart returns a drive's SMART samples, newest first, optionally with
	// the latest raw smartctl output.
	GetSmart(context.Context, *connect.Request[drivelistv1.GetSmartRequest]) (*connect.Response[drivelistv1.GetSmartResponse], error)
	// GetIO returns a drive's I/O buckets, newest first.
	GetIO(context.Context, *connect.Request[drivelistv1.GetIORequest]) (*connect.Response[drivelistv1.GetIOResponse], error)
	// CompareIO returns every currently placed drive's latency and
	// utilisation over a window next to the median of its vdev, so an
	// outlier among identical drives stands out.
	CompareIO(context.Context, *connect.Request[drivelistv1.CompareIORequest]) (*connect.Response[drivelistv1.CompareIOResponse], error)
	// MergeDrives folds one drive record into another: use it when one
	// physical drive got two records, such as from being seen once without
	// its WWN. Everything moves to `into`; `from` keeps resolving to it.
	MergeDrives(context.Context, *connect.Request[drivelistv1.MergeDrivesRequest]) (*connect.Response[drivelistv1.MergeDrivesResponse], error)
	// MergeHosts folds one host record into another, for a host reinstalled
	// with a new machine id. Refs are hostnames or machine ids.
	MergeHosts(context.Context, *connect.Request[drivelistv1.MergeHostsRequest]) (*connect.Response[drivelistv1.MergeHostsResponse], error)
	// Rebuild recomputes every placement and derived event from the stored
	// snapshots. Annotations, merges, samples and ghosts are kept.
	Rebuild(context.Context, *connect.Request[drivelistv1.RebuildRequest]) (*connect.Response[drivelistv1.RebuildResponse], error)
	// ListEnclosures lists the enclosures drives sit in.
	ListEnclosures(context.Context, *connect.Request[drivelistv1.ListEnclosuresRequest]) (*connect.Response[drivelistv1.ListEnclosuresResponse], error)
	// NameEnclosure records what a person calls an enclosure; every view
	// shows the name in place of the kernel's expander-H:N from then on.
	NameEnclosure(context.Context, *connect.Request[drivelistv1.NameEnclosureRequest]) (*connect.Response[drivelistv1.NameEnclosureResponse], error)
	// GetSAS returns one host's SAS topology as the server last saw it.
	GetSAS(context.Context, *connect.Request[drivelistv1.GetSASRequest]) (*connect.Response[drivelistv1.GetSASResponse], error)
	// ListSASErrors lists the phys whose error counters climbed in a window.
	ListSASErrors(context.Context, *connect.Request[drivelistv1.ListSASErrorsRequest]) (*connect.Response[drivelistv1.ListSASErrorsResponse], error)
}

// NewQueryHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewQueryHandler(svc QueryHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	queryMethods := drivelistv1.File_drivelist_v1_drivelist_proto.Services().ByName("Query").Methods()
	queryListHostsHandler := connect.NewUnaryHandler(
		QueryListHostsProcedure,
		svc.ListHosts,
		connect.WithSchema(queryMethods.ByName("ListHosts")),
		connect.WithHandlerOptions(opts...),
	)
	queryListDrivesHandler := connect.NewUnaryHandler(
		QueryListDrivesProcedure,
		svc.ListDrives,
		connect.WithSchema(queryMethods.ByName("ListDrives")),
		connect.WithHandlerOptions(opts...),
	)
	queryGetDriveHandler := connect.NewUnaryHandler(
		QueryGetDriveProcedure,
		svc.GetDrive,
		connect.WithSchema(queryMethods.ByName("GetDrive")),
		connect.WithHandlerOptions(opts...),
	)
	queryGetDriveHistoryHandler := connect.NewUnaryHandler(
		QueryGetDriveHistoryProcedure,
		svc.GetDriveHistory,
		connect.WithSchema(queryMethods.ByName("GetDriveHistory")),
		connect.WithHandlerOptions(opts...),
	)
	queryListEventsHandler := connect.NewUnaryHandler(
		QueryListEventsProcedure,
		svc.ListEvents,
		connect.WithSchema(queryMethods.ByName("ListEvents")),
		connect.WithHandlerOptions(opts...),
	)
	queryListMissingHandler := connect.NewUnaryHandler(
		QueryListMissingProcedure,
		svc.ListMissing,
		connect.WithSchema(queryMethods.ByName("ListMissing")),
		connect.WithHandlerOptions(opts...),
	)
	queryAnnotateHandler := connect.NewUnaryHandler(
		QueryAnnotateProcedure,
		svc.Annotate,
		connect.WithSchema(queryMethods.ByName("Annotate")),
		connect.WithHandlerOptions(opts...),
	)
	queryGetKernelHandler := connect.NewUnaryHandler(
		QueryGetKernelProcedure,
		svc.GetKernel,
		connect.WithSchema(queryMethods.ByName("GetKernel")),
		connect.WithHandlerOptions(opts...),
	)
	queryGetSmartHandler := connect.NewUnaryHandler(
		QueryGetSmartProcedure,
		svc.GetSmart,
		connect.WithSchema(queryMethods.ByName("GetSmart")),
		connect.WithHandlerOptions(opts...),
	)
	queryGetIOHandler := connect.NewUnaryHandler(
		QueryGetIOProcedure,
		svc.GetIO,
		connect.WithSchema(queryMethods.ByName("GetIO")),
		connect.WithHandlerOptions(opts...),
	)
	queryCompareIOHandler := connect.NewUnaryHandler(
		QueryCompareIOProcedure,
		svc.CompareIO,
		connect.WithSchema(queryMethods.ByName("CompareIO")),
		connect.WithHandlerOptions(opts...),
	)
	queryMergeDrivesHandler := connect.NewUnaryHandler(
		QueryMergeDrivesProcedure,
		svc.MergeDrives,
		connect.WithSchema(queryMethods.ByName("MergeDrives")),
		connect.WithHandlerOptions(opts...),
	)
	queryMergeHostsHandler := connect.NewUnaryHandler(
		QueryMergeHostsProcedure,
		svc.MergeHosts,
		connect.WithSchema(queryMethods.ByName("MergeHosts")),
		connect.WithHandlerOptions(opts...),
	)
	queryRebuildHandler := connect.NewUnaryHandler(
		QueryRebuildProcedure,
		svc.Rebuild,
		connect.WithSchema(queryMethods.ByName("Rebuild")),
		connect.WithHandlerOptions(opts...),
	)
	queryListEnclosuresHandler := connect.NewUnaryHandler(
		QueryListEnclosuresProcedure,
		svc.ListEnclosures,
		connect.WithSchema(queryMethods.ByName("ListEnclosures")),
		connect.WithHandlerOptions(opts...),
	)
	queryNameEnclosureHandler := connect.NewUnaryHandler(
		QueryNameEnclosureProcedure,
		svc.NameEnclosure,
		connect.WithSchema(queryMethods.ByName("NameEnclosure")),
		connect.WithHandlerOptions(opts...),
	)
	queryGetSASHandler := connect.NewUnaryHandler(
		QueryGetSASProcedure,
		svc.GetSAS,
		connect.WithSchema(queryMethods.ByName("GetSAS")),
		connect.WithHandlerOptions(opts...),
	)
	queryListSASErrorsHandler := connect.NewUnaryHandler(
		QueryListSASErrorsProcedure,
		svc.ListSASErrors,
		connect.WithSchema(queryMethods.ByName("ListSASErrors")),
		connect.WithHandlerOptions(opts...),
	)
	return "/drivelist.v1.Query/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case QueryListHostsProcedure:
			queryListHostsHandler.ServeHTTP(w, r)
		case QueryListDrivesProcedure:
			queryListDrivesHandler.ServeHTTP(w, r)
		case QueryGetDriveProcedure:
			queryGetDriveHandler.ServeHTTP(w, r)
		case QueryGetDriveHistoryProcedure:
			queryGetDriveHistoryHandler.ServeHTTP(w, r)
		case QueryListEventsProcedure:
			queryListEventsHandler.ServeHTTP(w, r)
		case QueryListMissingProcedure:
			queryListMissingHandler.ServeHTTP(w, r)
		case QueryAnnotateProcedure:
			queryAnnotateHandler.ServeHTTP(w, r)
		case QueryGetKernelProcedure:
			queryGetKernelHandler.ServeHTTP(w, r)
		case QueryGetSmartProcedure:
			queryGetSmartHandler.ServeHTTP(w, r)
		case QueryGetIOProcedure:
			queryGetIOHandler.ServeHTTP(w, r)
		case QueryCompareIOProcedure:
			queryCompareIOHandler.ServeHTTP(w, r)
		case QueryMergeDrivesProcedure:
			queryMergeDrivesHandler.ServeHTTP(w, r)
		case QueryMergeHostsProcedure:
			queryMergeHostsHandler.ServeHTTP(w, r)
		case QueryRebuildProcedure:
			queryRebuildHandler.ServeHTTP(w, r)
		case QueryListEnclosuresProcedure:
			queryListEnclosuresHandler.ServeHTTP(w, r)
		case QueryNameEnclosureProcedure:
			queryNameEnclosureHandler.ServeHTTP(w, r)
		case QueryGetSASProcedure:
			queryGetSASHandler.ServeHTTP(w, r)
		case QueryListSASErrorsProcedure:
			queryListSASErrorsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedQueryHandler returns CodeUnimplemented from all methods.
type UnimplementedQueryHandler struct{}

func (UnimplementedQueryHandler) ListHosts(context.Context, *connect.Request[drivelistv1.ListHostsRequest]) (*connect.Response[drivelistv1.ListHostsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.ListHosts is not implemented"))
}

func (UnimplementedQueryHandler) ListDrives(context.Context, *connect.Request[drivelistv1.ListDrivesRequest]) (*connect.Response[drivelistv1.ListDrivesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.ListDrives is not implemented"))
}

func (UnimplementedQueryHandler) GetDrive(context.Context, *connect.Request[drivelistv1.GetDriveRequest]) (*connect.Response[drivelistv1.GetDriveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.GetDrive is not implemented"))
}

func (UnimplementedQueryHandler) GetDriveHistory(context.Context, *connect.Request[drivelistv1.GetDriveHistoryRequest]) (*connect.Response[drivelistv1.GetDriveHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.GetDriveHistory is not implemented"))
}

func (UnimplementedQueryHandler) ListEvents(context.Context, *connect.Request[drivelistv1.ListEventsRequest]) (*connect.Response[drivelistv1.ListEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.ListEvents is not implemented"))
}

func (UnimplementedQueryHandler) ListMissing(context.Context, *connect.Request[drivelistv1.ListMissingRequest]) (*connect.Response[drivelistv1.ListMissingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.ListMissing is not implemented"))
}

func (UnimplementedQueryHandler) Annotate(context.Context, *connect.Request[drivelistv1.AnnotateRequest]) (*connect.Response[drivelistv1.AnnotateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.Annotate is not implemented"))
}

func (UnimplementedQueryHandler) GetKernel(context.Context, *connect.Request[drivelistv1.GetKernelRequest]) (*connect.Response[drivelistv1.GetKernelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.GetKernel is not implemented"))
}

func (UnimplementedQueryHandler) GetSmart(context.Context, *connect.Request[drivelistv1.GetSmartRequest]) (*connect.Response[drivelistv1.GetSmartResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.GetSmart is not implemented"))
}

func (UnimplementedQueryHandler) GetIO(context.Context, *connect.Request[drivelistv1.GetIORequest]) (*connect.Response[drivelistv1.GetIOResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.GetIO is not implemented"))
}

func (UnimplementedQueryHandler) CompareIO(context.Context, *connect.Request[drivelistv1.CompareIORequest]) (*connect.Response[drivelistv1.CompareIOResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.CompareIO is not implemented"))
}

func (UnimplementedQueryHandler) MergeDrives(context.Context, *connect.Request[drivelistv1.MergeDrivesRequest]) (*connect.Response[drivelistv1.MergeDrivesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.MergeDrives is not implemented"))
}

func (UnimplementedQueryHandler) MergeHosts(context.Context, *connect.Request[drivelistv1.MergeHostsRequest]) (*connect.Response[drivelistv1.MergeHostsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.MergeHosts is not implemented"))
}

func (UnimplementedQueryHandler) Rebuild(context.Context, *connect.Request[drivelistv1.RebuildRequest]) (*connect.Response[drivelistv1.RebuildResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.Rebuild is not implemented"))
}

func (UnimplementedQueryHandler) ListEnclosures(context.Context, *connect.Request[drivelistv1.ListEnclosuresRequest]) (*connect.Response[drivelistv1.ListEnclosuresResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.ListEnclosures is not implemented"))
}

func (UnimplementedQueryHandler) NameEnclosure(context.Context, *connect.Request[drivelistv1.NameEnclosureRequest]) (*connect.Response[drivelistv1.NameEnclosureResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.NameEnclosure is not implemented"))
}

func (UnimplementedQueryHandler) GetSAS(context.Context, *connect.Request[drivelistv1.GetSASRequest]) (*connect.Response[drivelistv1.GetSASResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.GetSAS is not implemented"))
}

func (UnimplementedQueryHandler) ListSASErrors(context.Context, *connect.Request[drivelistv1.ListSASErrorsRequest]) (*connect.Response[drivelistv1.ListSASErrorsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.ListSASErrors is not implemented"))
}
