// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: drivelist/v1/drivelist.proto

package drivelistv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	drivelistv1 "github.com/scottlaird/drivelist/internal/pb/drivelistv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CollectorName is the fully-qualified name of the Collector service.
	CollectorName = "drivelist.v1.Collector"
	// QueryName is the fully-qualified name of the Query service.
	QueryName = "drivelist.v1.Query"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CollectorReportInventoryProcedure is the fully-qualified name of the Collector's ReportInventory
	// RPC.
	CollectorReportInventoryProcedure = "/drivelist.v1.Collector/ReportInventory"
	// CollectorReportKernelProcedure is the fully-qualified name of the Collector's ReportKernel RPC.
	CollectorReportKernelProcedure = "/drivelist.v1.Collector/ReportKernel"
	// QueryListHostsProcedure is the fully-qualified name of the Query's ListHosts RPC.
	QueryListHostsProcedure = "/drivelist.v1.Query/ListHosts"
	// QueryListDrivesProcedure is the fully-qualified name of the Query's ListDrives RPC.
	QueryListDrivesProcedure = "/drivelist.v1.Query/ListDrives"
	// QueryGetDriveProcedure is the fully-qualified name of the Query's GetDrive RPC.
	QueryGetDriveProcedure = "/drivelist.v1.Query/GetDrive"
	// QueryGetDriveHistoryProcedure is the fully-qualified name of the Query's GetDriveHistory RPC.
	QueryGetDriveHistoryProcedure = "/drivelist.v1.Query/GetDriveHistory"
	// QueryListEventsProcedure is the fully-qualified name of the Query's ListEvents RPC.
	QueryListEventsProcedure = "/drivelist.v1.Query/ListEvents"
	// QueryListMissingProcedure is the fully-qualified name of the Query's ListMissing RPC.
	QueryListMissingProcedure = "/drivelist.v1.Query/ListMissing"
	// QueryAnnotateProcedure is the fully-qualified name of the Query's Annotate RPC.
	QueryAnnotateProcedure = "/drivelist.v1.Query/Annotate"
	// QueryGetKernelProcedure is the fully-qualified name of the Query's GetKernel RPC.
	QueryGetKernelProcedure = "/drivelist.v1.Query/GetKernel"
)

// CollectorClient is a client for the drivelist.v1.Collector service.
type CollectorClient interface {
	// ReportInventory posts the complete current inventory of one host.
	ReportInventory(context.Context, *connect.Request[drivelistv1.ReportInventoryRequest]) (*connect.Response[drivelistv1.ReportInventoryResponse], error)
	// ReportKernel posts hourly counts of classified kernel log lines per
	// drive. Each bucket is sent once, complete; resending replaces.
	ReportKernel(context.Context, *connect.Request[drivelistv1.ReportKernelRequest]) (*connect.Response[drivelistv1.ReportAck], error)
}

// NewCollectorClient constructs a client for the drivelist.v1.Collector service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCollectorClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CollectorClient {
	baseURL = strings.TrimRight(baseURL, "/")
	collectorMethods := drivelistv1.File_drivelist_v1_drivelist_proto.Services().ByName("Collector").Methods()
	return &collectorClient{
		reportInventory: connect.NewClient[drivelistv1.ReportInventoryRequest, drivelistv1.ReportInventoryResponse](
			httpClient,
			baseURL+CollectorReportInventoryProcedure,
			connect.WithSchema(collectorMethods.ByName("ReportInventory")),
			connect.WithClientOptions(opts...),
		),
		reportKernel: connect.NewClient[drivelistv1.ReportKernelRequest, drivelistv1.ReportAck](
			httpClient,
			baseURL+CollectorReportKernelProcedure,
			connect.WithSchema(collectorMethods.ByName("ReportKernel")),
			connect.WithClientOptions(opts...),
		),
	}
}

// collectorClient implements CollectorClient.
type collectorClient struct {
	reportInventory *connect.Client[drivelistv1.ReportInventoryRequest, drivelistv1.ReportInventoryResponse]
	reportKernel    *connect.Client[drivelistv1.ReportKernelRequest, drivelistv1.ReportAck]
}

// ReportInventory calls drivelist.v1.Collector.ReportInventory.
func (c *collectorClient) ReportInventory(ctx context.Context, req *connect.Request[drivelistv1.ReportInventoryRequest]) (*connect.Response[drivelistv1.ReportInventoryResponse], error) {
	return c.reportInventory.CallUnary(ctx, req)
}

// ReportKernel calls drivelist.v1.Collector.ReportKernel.
func (c *collectorClient) ReportKernel(ctx context.Context, req *connect.Request[drivelistv1.ReportKernelRequest]) (*connect.Response[drivelistv1.ReportAck], error) {
	return c.reportKernel.CallUnary(ctx, req)
}

// CollectorHandler is an implementation of the drivelist.v1.Collector service.
type CollectorHandler interface {
	// ReportInventory posts the complete current inventory of one host.
	ReportInventory(context.Context, *connect.Request[drivelistv1.ReportInventoryRequest]) (*connect.Response[drivelistv1.ReportInventoryResponse], error)
	// ReportKernel posts hourly counts of classified kernel log lines per
	// drive. Each bucket is sent once, complete; resending replaces.
	ReportKernel(context.Context, *connect.Request[drivelistv1.ReportKernelRequest]) (*connect.Response[drivelistv1.ReportAck], error)
}

// NewCollectorHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCollectorHandler(svc CollectorHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	collectorMethods := drivelistv1.File_drivelist_v1_drivelist_proto.Services().ByName("Collector").Methods()
	collectorReportInventoryHandler := connect.NewUnaryHandler(
		CollectorReportInventoryProcedure,
		svc.ReportInventory,
		connect.WithSchema(collectorMethods.ByName("ReportInventory")),
		connect.WithHandlerOptions(opts...),
	)
	collectorReportKernelHandler := connect.NewUnaryHandler(
		CollectorReportKernelProcedure,
		svc.ReportKernel,
		connect.WithSchema(collectorMethods.ByName("ReportKernel")),
		connect.WithHandlerOptions(opts...),
	)
	return "/drivelist.v1.Collector/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CollectorReportInventoryProcedure:
			collectorReportInventoryHandler.ServeHTTP(w, r)
		case CollectorReportKernelProcedure:
			collectorReportKernelHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCollectorHandler returns CodeUnimplemented from all methods.
type UnimplementedCollectorHandler struct{}

func (UnimplementedCollectorHandler) ReportInventory(context.Context, *connect.Request[drivelistv1.ReportInventoryRequest]) (*connect.Response[drivelistv1.ReportInventoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Collector.ReportInventory is not implemented"))
}

func (UnimplementedCollectorHandler) ReportKernel(context.Context, *connect.Request[drivelistv1.ReportKernelRequest]) (*connect.Response[drivelistv1.ReportAck], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Collector.ReportKernel is not implemented"))
}

// QueryClient is a client for the drivelist.v1.Query service.
type QueryClient interface {
	ListHosts(context.Context, *connect.Request[drivelistv1.ListHostsRequest]) (*connect.Response[drivelistv1.ListHostsResponse], error)
	ListDrives(context.Context, *connect.Request[drivelistv1.ListDrivesRequest]) (*connect.Response[drivelistv1.ListDrivesResponse], error)
	// GetDrive resolves a serial, WWN, or unambiguous prefix of either.
	GetDrive(context.Context, *connect.Request[drivelistv1.GetDriveRequest]) (*connect.Response[drivelistv1.GetDriveResponse], error)
	// GetDriveHistory returns every placement and event for one drive,
	// oldest first.
	GetDriveHistory(context.Context, *connect.Request[drivelistv1.GetDriveHistoryRequest]) (*connect.Response[drivelistv1.GetDriveHistoryResponse], error)
	ListEvents(context.Context, *connect.Request[drivelistv1.ListEventsRequest]) (*connect.Response[drivelistv1.ListEventsResponse], error)
	// ListMissing returns drives whose last placement ended with vanished and
	// whose status does not expect absence, plus open pool ghosts.
	ListMissing(context.Context, *connect.Request[drivelistv1.ListMissingRequest]) (*connect.Response[drivelistv1.ListMissingResponse], error)
	// Annotate records a manual status change or note as an event.
	Annotate(context.Context, *connect.Request[drivelistv1.AnnotateRequest]) (*connect.Response[drivelistv1.AnnotateResponse], error)
	// GetKernel returns a drive's kernel log counts, newest bucket first.
	GetKernel(context.Context, *connect.Request[drivelistv1.GetKernelRequest]) (*connect.Response[drivelistv1.GetKernelResponse], error)
}

// NewQueryClient constructs a client for the drivelist.v1.Query service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewQueryClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) QueryClient {
	baseURL = strings.TrimRight(baseURL, "/")
	queryMethods := drivelistv1.File_drivelist_v1_drivelist_proto.Services().ByName("Query").Methods()
	return &queryClient{
		listHosts: connect.NewClient[drivelistv1.ListHostsRequest, drivelistv1.ListHostsResponse](
			httpClient,
			baseURL+QueryListHostsProcedure,
			connect.WithSchema(queryMethods.ByName("ListHosts")),
			connect.WithClientOptions(opts...),
		),
		listDrives: connect.NewClient[drivelistv1.ListDrivesRequest, drivelistv1.ListDrivesResponse](
			httpClient,
			baseURL+QueryListDrivesProcedure,
			connect.WithSchema(queryMethods.ByName("ListDrives")),
			connect.WithClientOptions(opts...),
		),
		getDrive: connect.NewClient[drivelistv1.GetDriveRequest, drivelistv1.GetDriveResponse](
			httpClient,
			baseURL+QueryGetDriveProcedure,
			connect.WithSchema(queryMethods.ByName("GetDrive")),
			connect.WithClientOptions(opts...),
		),
		getDriveHistory: connect.NewClient[drivelistv1.GetDriveHistoryRequest, drivelistv1.GetDriveHistoryResponse](
			httpClient,
			baseURL+QueryGetDriveHistoryProcedure,
			connect.WithSchema(queryMethods.ByName("GetDriveHistory")),
			connect.WithClientOptions(opts...),
		),
		listEvents: connect.NewClient[drivelistv1.ListEventsRequest, drivelistv1.ListEventsResponse](
			httpClient,
			baseURL+QueryListEventsProcedure,
			connect.WithSchema(queryMethods.ByName("ListEvents")),
			connect.WithClientOptions(opts...),
		),
		listMissing: connect.NewClient[drivelistv1.ListMissingRequest, drivelistv1.ListMissingResponse](
			httpClient,
			baseURL+QueryListMissingProcedure,
			connect.WithSchema(queryMethods.ByName("ListMissing")),
			connect.WithClientOptions(opts...),
		),
		annotate: connect.NewClient[drivelistv1.AnnotateRequest, drivelistv1.AnnotateResponse](
			httpClient,
			baseURL+QueryAnnotateProcedure,
			connect.WithSchema(queryMethods.ByName("Annotate")),
			connect.WithClientOptions(opts...),
		),
		getKernel: connect.NewClient[drivelistv1.GetKernelRequest, drivelistv1.GetKernelResponse](
			httpClient,
			baseURL+QueryGetKernelProcedure,
			connect.WithSchema(queryMethods.ByName("GetKernel")),
			connect.WithClientOptions(opts...),
		),
	}
}

// queryClient implements QueryClient.
type queryClient struct {
	listHosts       *connect.Client[drivelistv1.ListHostsRequest, drivelistv1.ListHostsResponse]
	listDrives      *connect.Client[drivelistv1.ListDrivesRequest, drivelistv1.ListDrivesResponse]
	getDrive        *connect.Client[drivelistv1.GetDriveRequest, drivelistv1.GetDriveResponse]
	getDriveHistory *connect.Client[drivelistv1.GetDriveHistoryRequest, drivelistv1.GetDriveHistoryResponse]
	listEvents      *connect.Client[drivelistv1.ListEventsRequest, drivelistv1.ListEventsResponse]
	listMissing     *connect.Client[drivelistv1.ListMissingRequest, drivelistv1.ListMissingResponse]
	annotate        *connect.Client[drivelistv1.AnnotateRequest, drivelistv1.AnnotateResponse]
	getKernel       *connect.Client[drivelistv1.GetKernelRequest, drivelistv1.GetKernelResponse]
}

// ListHosts calls drivelist.v1.Query.ListHosts.
func (c *queryClient) ListHosts(ctx context.Context, req *connect.Request[drivelistv1.ListHostsRequest]) (*connect.Response[drivelistv1.ListHostsResponse], error) {
	return c.listHosts.CallUnary(ctx, req)
}

// ListDrives calls drivelist.v1.Query.ListDrives.
func (c *queryClient) ListDrives(ctx context.Context, req *connect.Request[drivelistv1.ListDrivesRequest]) (*connect.Response[drivelistv1.ListDrivesResponse], error) {
	return c.listDrives.CallUnary(ctx, req)
}

// GetDrive calls drivelist.v1.Query.GetDrive.
func (c *queryClient) GetDrive(ctx context.Context, req *connect.Request[drivelistv1.GetDriveRequest]) (*connect.Response[drivelistv1.GetDriveResponse], error) {
	return c.getDrive.CallUnary(ctx, req)
}

// GetDriveHistory calls drivelist.v1.Query.GetDriveHistory.
func (c *queryClient) GetDriveHistory(ctx context.Context, req *connect.Request[drivelistv1.GetDriveHistoryRequest]) (*connect.Response[drivelistv1.GetDriveHistoryResponse], error) {
	return c.getDriveHistory.CallUnary(ctx, req)
}

// ListEvents calls drivelist.v1.Query.ListEvents.
func (c *queryClient) ListEvents(ctx context.Context, req *connect.Request[drivelistv1.ListEventsRequest]) (*connect.Response[drivelistv1.ListEventsResponse], error) {
	return c.listEvents.CallUnary(ctx, req)
}

// ListMissing calls drivelist.v1.Query.ListMissing.
func (c *queryClient) ListMissing(ctx context.Context, req *connect.Request[drivelistv1.ListMissingRequest]) (*connect.Response[drivelistv1.ListMissingResponse], error) {
	return c.listMissing.CallUnary(ctx, req)
}

// Annotate calls drivelist.v1.Query.Annotate.
func (c *queryClient) Annotate(ctx context.Context, req *connect.Request[drivelistv1.AnnotateRequest]) (*connect.Response[drivelistv1.AnnotateResponse], error) {
	return c.annotate.CallUnary(ctx, req)
}

// GetKernel calls drivelist.v1.Query.GetKernel.
func (c *queryClient) GetKernel(ctx context.Context, req *connect.Request[drivelistv1.GetKernelRequest]) (*connect.Response[drivelistv1.GetKernelResponse], error) {
	return c.getKernel.CallUnary(ctx, req)
}

// QueryHandler is an implementation of the drivelist.v1.Query service.
type QueryHandler interface {
	ListHosts(context.Context, *connect.Request[drivelistv1.ListHostsRequest]) (*connect.Response[drivelistv1.ListHostsResponse], error)
	ListDrives(context.Context, *connect.Request[drivelistv1.ListDrivesRequest]) (*connect.Response[drivelistv1.ListDrivesResponse], error)
	// GetDrive resolves a serial, WWN, or unambiguous prefix of either.
	GetDrive(context.Context, *connect.Request[drivelistv1.GetDriveRequest]) (*connect.Response[drivelistv1.GetDriveResponse], error)
	// GetDriveHistory returns every placement and event for one drive,
	// oldest first.
	GetDriveHistory(context.Context, *connect.Request[drivelistv1.GetDriveHistoryRequest]) (*connect.Response[drivelistv1.GetDriveHistoryResponse], error)
	ListEvents(context.Context, *connect.Request[drivelistv1.ListEventsRequest]) (*connect.Response[drivelistv1.ListEventsResponse], error)
	// ListMissing returns drives whose last placement ended with vanished and
	// whose status does not expect absence, plus open pool ghosts.
	ListMissing(context.Context, *connect.Request[drivelistv1.ListMissingRequest]) (*connect.Response[drivelistv1.ListMissingResponse], error)
	// Annotate records a manual status change or note as an event.
	Annotate(context.Context, *connect.Request[drivelistv1.AnnotateRequest]) (*connect.Response[drivelistv1.AnnotateResponse], error)
	// GetKernel returns a drive's kernel log counts, newest bucket first.
	GetKernel(context.Context, *connect.Request[drivelistv1.GetKernelRequest]) (*connect.Response[drivelistv1.GetKernelResponse], error)
}

// NewQueryHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewQueryHandler(svc QueryHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	queryMethods := drivelistv1.File_drivelist_v1_drivelist_proto.Services().ByName("Query").Methods()
	queryListHostsHandler := connect.NewUnaryHandler(
		QueryListHostsProcedure,
		svc.ListHosts,
		connect.WithSchema(queryMethods.ByName("ListHosts")),
		connect.WithHandlerOptions(opts...),
	)
	queryListDrivesHandler := connect.NewUnaryHandler(
		QueryListDrivesProcedure,
		svc.ListDrives,
		connect.WithSchema(queryMethods.ByName("ListDrives")),
		connect.WithHandlerOptions(opts...),
	)
	queryGetDriveHandler := connect.NewUnaryHandler(
		QueryGetDriveProcedure,
		svc.GetDrive,
		connect.WithSchema(queryMethods.ByName("GetDrive")),
		connect.WithHandlerOptions(opts...),
	)
	queryGetDriveHistoryHandler := connect.NewUnaryHandler(
		QueryGetDriveHistoryProcedure,
		svc.GetDriveHistory,
		connect.WithSchema(queryMethods.ByName("GetDriveHistory")),
		connect.WithHandlerOptions(opts...),
	)
	queryListEventsHandler := connect.NewUnaryHandler(
		QueryListEventsProcedure,
		svc.ListEvents,
		connect.WithSchema(queryMethods.ByName("ListEvents")),
		connect.WithHandlerOptions(opts...),
	)
	queryListMissingHandler := connect.NewUnaryHandler(
		QueryListMissingProcedure,
		svc.ListMissing,
		connect.WithSchema(queryMethods.ByName("ListMissing")),
		connect.WithHandlerOptions(opts...),
	)
	queryAnnotateHandler := connect.NewUnaryHandler(
		QueryAnnotateProcedure,
		svc.Annotate,
		connect.WithSchema(queryMethods.ByName("Annotate")),
		connect.WithHandlerOptions(opts...),
	)
	queryGetKernelHandler := connect.NewUnaryHandler(
		QueryGetKernelProcedure,
		svc.GetKernel,
		connect.WithSchema(queryMethods.ByName("GetKernel")),
		connect.WithHandlerOptions(opts...),
	)
	return "/drivelist.v1.Query/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case QueryListHostsProcedure:
			queryListHostsHandler.ServeHTTP(w, r)
		case QueryListDrivesProcedure:
			queryListDrivesHandler.ServeHTTP(w, r)
		case QueryGetDriveProcedure:
			queryGetDriveHandler.ServeHTTP(w, r)
		case QueryGetDriveHistoryProcedure:
			queryGetDriveHistoryHandler.ServeHTTP(w, r)
		case QueryListEventsProcedure:
			queryListEventsHandler.ServeHTTP(w, r)
		case QueryListMissingProcedure:
			queryListMissingHandler.ServeHTTP(w, r)
		case QueryAnnotateProcedure:
			queryAnnotateHandler.ServeHTTP(w, r)
		case QueryGetKernelProcedure:
			queryGetKernelHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedQueryHandler returns CodeUnimplemented from all methods.
type UnimplementedQueryHandler struct{}

func (UnimplementedQueryHandler) ListHosts(context.Context, *connect.Request[drivelistv1.ListHostsRequest]) (*connect.Response[drivelistv1.ListHostsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.ListHosts is not implemented"))
}

func (UnimplementedQueryHandler) ListDrives(context.Context, *connect.Request[drivelistv1.ListDrivesRequest]) (*connect.Response[drivelistv1.ListDrivesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.ListDrives is not implemented"))
}

func (UnimplementedQueryHandler) GetDrive(context.Context, *connect.Request[drivelistv1.GetDriveRequest]) (*connect.Response[drivelistv1.GetDriveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.GetDrive is not implemented"))
}

func (UnimplementedQueryHandler) GetDriveHistory(context.Context, *connect.Request[drivelistv1.GetDriveHistoryRequest]) (*connect.Response[drivelistv1.GetDriveHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.GetDriveHistory is not implemented"))
}

func (UnimplementedQueryHandler) ListEvents(context.Context, *connect.Request[drivelistv1.ListEventsRequest]) (*connect.Response[drivelistv1.ListEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.ListEvents is not implemented"))
}

func (UnimplementedQueryHandler) ListMissing(context.Context, *connect.Request[drivelistv1.ListMissingRequest]) (*connect.Response[drivelistv1.ListMissingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.ListMissing is not implemented"))
}

func (UnimplementedQueryHandler) Annotate(context.Context, *connect.Request[drivelistv1.AnnotateRequest]) (*connect.Response[drivelistv1.AnnotateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.Annotate is not implemented"))
}

func (UnimplementedQueryHandler) GetKernel(context.Context, *connect.Request[drivelistv1.GetKernelRequest]) (*connect.Response[drivelistv1.GetKernelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("drivelist.v1.Query.GetKernel is not implemented"))
}
