// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: drivelist/v1/drivelist.proto

package drivelistv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bus int32

const (
	Bus_BUS_UNSPECIFIED Bus = 0
	Bus_BUS_SAS         Bus = 1
	Bus_BUS_SATA        Bus = 2
	Bus_BUS_NVME        Bus = 3
	Bus_BUS_USB         Bus = 4
	Bus_BUS_VIRTIO      Bus = 5
)

// Enum value maps for Bus.
var (
	Bus_name = map[int32]string{
		0: "BUS_UNSPECIFIED",
		1: "BUS_SAS",
		2: "BUS_SATA",
		3: "BUS_NVME",
		4: "BUS_USB",
		5: "BUS_VIRTIO",
	}
	Bus_value = map[string]int32{
		"BUS_UNSPECIFIED": 0,
		"BUS_SAS":         1,
		"BUS_SATA":        2,
		"BUS_NVME":        3,
		"BUS_USB":         4,
		"BUS_VIRTIO":      5,
	}
)

func (x Bus) Enum() *Bus {
	p := new(Bus)
	*p = x
	return p
}

func (x Bus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Bus) Descriptor() protoreflect.EnumDescriptor {
	return file_drivelist_v1_drivelist_proto_enumTypes[0].Descriptor()
}

func (Bus) Type() protoreflect.EnumType {
	return &file_drivelist_v1_drivelist_proto_enumTypes[0]
}

func (x Bus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Bus.Descriptor instead.
func (Bus) EnumDescriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{0}
}

type HostIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"` // /etc/machine-id or IOPlatformUUID; the key, never shown
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"` // "linux", "darwin"
	AgentVersion  string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostIdentity) Reset() {
	*x = HostIdentity{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostIdentity) ProtoMessage() {}

func (x *HostIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostIdentity.ProtoReflect.Descriptor instead.
func (*HostIdentity) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{0}
}

func (x *HostIdentity) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *HostIdentity) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HostIdentity) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HostIdentity) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

// DriveIdentity is how an agent names a drive. The server resolves it to a
// drive record through its keys; agents never see drive ids.
type DriveIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wwn           string                 `protobuf:"bytes,1,opt,name=wwn,proto3" json:"wwn,omitempty"` // "0x5000cca25206c808", "eui.…", or ""
	Vendor        string                 `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Serial        string                 `protobuf:"bytes,4,opt,name=serial,proto3" json:"serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriveIdentity) Reset() {
	*x = DriveIdentity{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriveIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriveIdentity) ProtoMessage() {}

func (x *DriveIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriveIdentity.ProtoReflect.Descriptor instead.
func (*DriveIdentity) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{1}
}

func (x *DriveIdentity) GetWwn() string {
	if x != nil {
		return x.Wwn
	}
	return ""
}

func (x *DriveIdentity) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *DriveIdentity) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DriveIdentity) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevName       string                 `protobuf:"bytes,1,opt,name=dev_name,json=devName,proto3" json:"dev_name,omitempty"` // "sdab", "nvme0n1"
	Identity      *DriveIdentity         `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	Bus           Bus                    `protobuf:"varint,3,opt,name=bus,proto3,enum=drivelist.v1.Bus" json:"bus,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Expander      string                 `protobuf:"bytes,5,opt,name=expander,proto3" json:"expander,omitempty"` // "expander-11:0"
	Bay           string                 `protobuf:"bytes,6,opt,name=bay,proto3" json:"bay,omitempty"`           // "54"
	EnclosurePath string                 `protobuf:"bytes,7,opt,name=enclosure_path,json=enclosurePath,proto3" json:"enclosure_path,omitempty"`
	Uses          []string               `protobuf:"bytes,8,rep,name=uses,proto3" json:"uses,omitempty"`                                   // "zfs > space … > disk …", "mount > /boot"
	DevLinks      []string               `protobuf:"bytes,9,rep,name=dev_links,json=devLinks,proto3" json:"dev_links,omitempty"`           // /dev/disk/by-id/…, used to match pool members
	Error         string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`                                // non-empty: identity unreadable; the report is degraded
	MemberState   string                 `protobuf:"bytes,11,opt,name=member_state,json=memberState,proto3" json:"member_state,omitempty"` // ZFS vdev state for the zfs use, "" otherwise
	ScsiAddr      string                 `protobuf:"bytes,12,opt,name=scsi_addr,json=scsiAddr,proto3" json:"scsi_addr,omitempty"`          // "11:0:17:0"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{2}
}

func (x *Device) GetDevName() string {
	if x != nil {
		return x.DevName
	}
	return ""
}

func (x *Device) GetIdentity() *DriveIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *Device) GetBus() Bus {
	if x != nil {
		return x.Bus
	}
	return Bus_BUS_UNSPECIFIED
}

func (x *Device) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Device) GetExpander() string {
	if x != nil {
		return x.Expander
	}
	return ""
}

func (x *Device) GetBay() string {
	if x != nil {
		return x.Bay
	}
	return ""
}

func (x *Device) GetEnclosurePath() string {
	if x != nil {
		return x.EnclosurePath
	}
	return ""
}

func (x *Device) GetUses() []string {
	if x != nil {
		return x.Uses
	}
	return nil
}

func (x *Device) GetDevLinks() []string {
	if x != nil {
		return x.DevLinks
	}
	return nil
}

func (x *Device) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Device) GetMemberState() string {
	if x != nil {
		return x.MemberState
	}
	return ""
}

func (x *Device) GetScsiAddr() string {
	if x != nil {
		return x.ScsiAddr
	}
	return ""
}

type EmptyBay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expander      string                 `protobuf:"bytes,1,opt,name=expander,proto3" json:"expander,omitempty"`
	Bay           string                 `protobuf:"bytes,2,opt,name=bay,proto3" json:"bay,omitempty"`
	EnclosurePath string                 `protobuf:"bytes,3,opt,name=enclosure_path,json=enclosurePath,proto3" json:"enclosure_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyBay) Reset() {
	*x = EmptyBay{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyBay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyBay) ProtoMessage() {}

func (x *EmptyBay) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyBay.ProtoReflect.Descriptor instead.
func (*EmptyBay) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{3}
}

func (x *EmptyBay) GetExpander() string {
	if x != nil {
		return x.Expander
	}
	return ""
}

func (x *EmptyBay) GetBay() string {
	if x != nil {
		return x.Bay
	}
	return ""
}

func (x *EmptyBay) GetEnclosurePath() string {
	if x != nil {
		return x.EnclosurePath
	}
	return ""
}

// UnmappedMember is a pool member the collector could not map to a Device.
type UnmappedMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pool          string                 `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Guid          string                 `protobuf:"bytes,3,opt,name=guid,proto3" json:"guid,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmappedMember) Reset() {
	*x = UnmappedMember{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmappedMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmappedMember) ProtoMessage() {}

func (x *UnmappedMember) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmappedMember.ProtoReflect.Descriptor instead.
func (*UnmappedMember) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{4}
}

func (x *UnmappedMember) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *UnmappedMember) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UnmappedMember) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *UnmappedMember) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type ReportInventoryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Host            *HostIdentity          `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	ObservedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Devices         []*Device              `protobuf:"bytes,3,rep,name=devices,proto3" json:"devices,omitempty"`
	EmptyBays       []*EmptyBay            `protobuf:"bytes,4,rep,name=empty_bays,json=emptyBays,proto3" json:"empty_bays,omitempty"`
	UnmappedMembers []*UnmappedMember      `protobuf:"bytes,5,rep,name=unmapped_members,json=unmappedMembers,proto3" json:"unmapped_members,omitempty"`
	Complete        bool                   `protobuf:"varint,6,opt,name=complete,proto3" json:"complete,omitempty"` // false if a collector stage failed outright
	CollectorErrors []string               `protobuf:"bytes,7,rep,name=collector_errors,json=collectorErrors,proto3" json:"collector_errors,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReportInventoryRequest) Reset() {
	*x = ReportInventoryRequest{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportInventoryRequest) ProtoMessage() {}

func (x *ReportInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportInventoryRequest.ProtoReflect.Descriptor instead.
func (*ReportInventoryRequest) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{5}
}

func (x *ReportInventoryRequest) GetHost() *HostIdentity {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *ReportInventoryRequest) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *ReportInventoryRequest) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *ReportInventoryRequest) GetEmptyBays() []*EmptyBay {
	if x != nil {
		return x.EmptyBays
	}
	return nil
}

func (x *ReportInventoryRequest) GetUnmappedMembers() []*UnmappedMember {
	if x != nil {
		return x.UnmappedMembers
	}
	return nil
}

func (x *ReportInventoryRequest) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *ReportInventoryRequest) GetCollectorErrors() []string {
	if x != nil {
		return x.CollectorErrors
	}
	return nil
}

// DriveStatus is the server's status for a drive, returned to the agent so
// the local listing can show it without network access.
type DriveStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *DriveIdentity         `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // ok | suspect | bad | shelved | retired
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriveStatus) Reset() {
	*x = DriveStatus{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriveStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriveStatus) ProtoMessage() {}

func (x *DriveStatus) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriveStatus.ProtoReflect.Descriptor instead.
func (*DriveStatus) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{6}
}

func (x *DriveStatus) GetIdentity() *DriveIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *DriveStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DriveStatus) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

// AgentConfig is server-driven cadence; the agent applies it on its next
// tick.
type AgentConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InventoryInterval *durationpb.Duration   `protobuf:"bytes,1,opt,name=inventory_interval,json=inventoryInterval,proto3" json:"inventory_interval,omitempty"`
	SmartInterval     *durationpb.Duration   `protobuf:"bytes,2,opt,name=smart_interval,json=smartInterval,proto3" json:"smart_interval,omitempty"`
	IoBucket          *durationpb.Duration   `protobuf:"bytes,3,opt,name=io_bucket,json=ioBucket,proto3" json:"io_bucket,omitempty"`
	CollectSmart      bool                   `protobuf:"varint,4,opt,name=collect_smart,json=collectSmart,proto3" json:"collect_smart,omitempty"`
	CollectIo         bool                   `protobuf:"varint,5,opt,name=collect_io,json=collectIo,proto3" json:"collect_io,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{7}
}

func (x *AgentConfig) GetInventoryInterval() *durationpb.Duration {
	if x != nil {
		return x.InventoryInterval
	}
	return nil
}

func (x *AgentConfig) GetSmartInterval() *durationpb.Duration {
	if x != nil {
		return x.SmartInterval
	}
	return nil
}

func (x *AgentConfig) GetIoBucket() *durationpb.Duration {
	if x != nil {
		return x.IoBucket
	}
	return nil
}

func (x *AgentConfig) GetCollectSmart() bool {
	if x != nil {
		return x.CollectSmart
	}
	return false
}

func (x *AgentConfig) GetCollectIo() bool {
	if x != nil {
		return x.CollectIo
	}
	return false
}

type ReportInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason  string                 `protobuf:"bytes,2,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"` // "clock_skew", "stale", "malformed"
	Changed       bool                   `protobuf:"varint,3,opt,name=changed,proto3" json:"changed,omitempty"`                              // the state differed from the previous snapshot
	Statuses      []*DriveStatus         `protobuf:"bytes,4,rep,name=statuses,proto3" json:"statuses,omitempty"`
	Config        *AgentConfig           `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportInventoryResponse) Reset() {
	*x = ReportInventoryResponse{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportInventoryResponse) ProtoMessage() {}

func (x *ReportInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportInventoryResponse.ProtoReflect.Descriptor instead.
func (*ReportInventoryResponse) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{8}
}

func (x *ReportInventoryResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ReportInventoryResponse) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *ReportInventoryResponse) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *ReportInventoryResponse) GetStatuses() []*DriveStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *ReportInventoryResponse) GetConfig() *AgentConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type Host struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	MachineId     string                 `protobuf:"bytes,2,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	FirstSeen     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastReport    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_report,json=lastReport,proto3" json:"last_report,omitempty"`
	StaleSince    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=stale_since,json=staleSince,proto3" json:"stale_since,omitempty"`        // unset when the host is reporting
	DriveCount    int32                  `protobuf:"varint,8,opt,name=drive_count,json=driveCount,proto3" json:"drive_count,omitempty"`       // open placements
	MissingCount  int32                  `protobuf:"varint,9,opt,name=missing_count,json=missingCount,proto3" json:"missing_count,omitempty"` // drives that vanished from this host and are not back
	GhostCount    int32                  `protobuf:"varint,10,opt,name=ghost_count,json=ghostCount,proto3" json:"ghost_count,omitempty"`      // open pool ghosts
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{9}
}

func (x *Host) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Host) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *Host) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Host) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Host) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *Host) GetLastReport() *timestamppb.Timestamp {
	if x != nil {
		return x.LastReport
	}
	return nil
}

func (x *Host) GetStaleSince() *timestamppb.Timestamp {
	if x != nil {
		return x.StaleSince
	}
	return nil
}

func (x *Host) GetDriveCount() int32 {
	if x != nil {
		return x.DriveCount
	}
	return 0
}

func (x *Host) GetMissingCount() int32 {
	if x != nil {
		return x.MissingCount
	}
	return 0
}

func (x *Host) GetGhostCount() int32 {
	if x != nil {
		return x.GhostCount
	}
	return 0
}

type Placement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Expander      string                 `protobuf:"bytes,2,opt,name=expander,proto3" json:"expander,omitempty"`
	Bay           string                 `protobuf:"bytes,3,opt,name=bay,proto3" json:"bay,omitempty"`
	DevName       string                 `protobuf:"bytes,4,opt,name=dev_name,json=devName,proto3" json:"dev_name,omitempty"`
	Uses          []string               `protobuf:"bytes,5,rep,name=uses,proto3" json:"uses,omitempty"`
	FirstSeen     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`    // last heartbeat that confirmed it
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`       // unset while current
	EndReason     string                 `protobuf:"bytes,9,opt,name=end_reason,json=endReason,proto3" json:"end_reason,omitempty"` // vanished | moved | use_changed | merged
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Placement) Reset() {
	*x = Placement{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Placement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Placement) ProtoMessage() {}

func (x *Placement) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Placement.ProtoReflect.Descriptor instead.
func (*Placement) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{10}
}

func (x *Placement) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Placement) GetExpander() string {
	if x != nil {
		return x.Expander
	}
	return ""
}

func (x *Placement) GetBay() string {
	if x != nil {
		return x.Bay
	}
	return ""
}

func (x *Placement) GetDevName() string {
	if x != nil {
		return x.DevName
	}
	return ""
}

func (x *Placement) GetUses() []string {
	if x != nil {
		return x.Uses
	}
	return nil
}

func (x *Placement) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *Placement) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *Placement) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *Placement) GetEndReason() string {
	if x != nil {
		return x.EndReason
	}
	return ""
}

type Drive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriveId       int64                  `protobuf:"varint,1,opt,name=drive_id,json=driveId,proto3" json:"drive_id,omitempty"`
	Wwn           string                 `protobuf:"bytes,2,opt,name=wwn,proto3" json:"wwn,omitempty"`
	Vendor        string                 `protobuf:"bytes,3,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Serial        string                 `protobuf:"bytes,5,opt,name=serial,proto3" json:"serial,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Bus           Bus                    `protobuf:"varint,7,opt,name=bus,proto3,enum=drivelist.v1.Bus" json:"bus,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	FirstSeen     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Current       *Placement             `protobuf:"bytes,11,opt,name=current,proto3" json:"current,omitempty"` // unset when the drive is not currently placed
	Last          *Placement             `protobuf:"bytes,12,opt,name=last,proto3" json:"last,omitempty"`       // the most recent placement when current is unset
	MemberState   string                 `protobuf:"bytes,13,opt,name=member_state,json=memberState,proto3" json:"member_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drive) Reset() {
	*x = Drive{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drive) ProtoMessage() {}

func (x *Drive) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drive.ProtoReflect.Descriptor instead.
func (*Drive) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{11}
}

func (x *Drive) GetDriveId() int64 {
	if x != nil {
		return x.DriveId
	}
	return 0
}

func (x *Drive) GetWwn() string {
	if x != nil {
		return x.Wwn
	}
	return ""
}

func (x *Drive) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *Drive) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Drive) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *Drive) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Drive) GetBus() Bus {
	if x != nil {
		return x.Bus
	}
	return Bus_BUS_UNSPECIFIED
}

func (x *Drive) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Drive) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *Drive) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *Drive) GetCurrent() *Placement {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *Drive) GetLast() *Placement {
	if x != nil {
		return x.Last
	}
	return nil
}

func (x *Drive) GetMemberState() string {
	if x != nil {
		return x.MemberState
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Serial        string                 `protobuf:"bytes,4,opt,name=serial,proto3" json:"serial,omitempty"` // of the drive, when the event is about one
	Wwn           string                 `protobuf:"bytes,5,opt,name=wwn,proto3" json:"wwn,omitempty"`
	Hostname      string                 `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"` // when the event is about, or happened on, a host
	Detail        string                 `protobuf:"bytes,7,opt,name=detail,proto3" json:"detail,omitempty"`     // JSON object; keys depend on kind
	Source        string                 `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`     // "snapshot:123" | "user:scott@laptop" | "sweeper"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{12}
}

func (x *Event) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *Event) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Event) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Event) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *Event) GetWwn() string {
	if x != nil {
		return x.Wwn
	}
	return ""
}

func (x *Event) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Event) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ListHostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHostsRequest) Reset() {
	*x = ListHostsRequest{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostsRequest) ProtoMessage() {}

func (x *ListHostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostsRequest.ProtoReflect.Descriptor instead.
func (*ListHostsRequest) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{13}
}

type ListHostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []*Host                `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHostsResponse) Reset() {
	*x = ListHostsResponse{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostsResponse) ProtoMessage() {}

func (x *ListHostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostsResponse.ProtoReflect.Descriptor instead.
func (*ListHostsResponse) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{14}
}

func (x *ListHostsResponse) GetHosts() []*Host {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type ListDrivesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`     // hostname or unambiguous prefix; "" = all
	Status        []string               `protobuf:"bytes,2,rep,name=status,proto3" json:"status,omitempty"` // filter: ok suspect bad shelved retired
	UnusedOnly    bool                   `protobuf:"varint,3,opt,name=unused_only,json=unusedOnly,proto3" json:"unused_only,omitempty"`
	MissingOnly   bool                   `protobuf:"varint,4,opt,name=missing_only,json=missingOnly,proto3" json:"missing_only,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"` // substring match
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDrivesRequest) Reset() {
	*x = ListDrivesRequest{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDrivesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDrivesRequest) ProtoMessage() {}

func (x *ListDrivesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDrivesRequest.ProtoReflect.Descriptor instead.
func (*ListDrivesRequest) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{15}
}

func (x *ListDrivesRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ListDrivesRequest) GetStatus() []string {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListDrivesRequest) GetUnusedOnly() bool {
	if x != nil {
		return x.UnusedOnly
	}
	return false
}

func (x *ListDrivesRequest) GetMissingOnly() bool {
	if x != nil {
		return x.MissingOnly
	}
	return false
}

func (x *ListDrivesRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type ListDrivesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drives        []*Drive               `protobuf:"bytes,1,rep,name=drives,proto3" json:"drives,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDrivesResponse) Reset() {
	*x = ListDrivesResponse{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDrivesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDrivesResponse) ProtoMessage() {}

func (x *ListDrivesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDrivesResponse.ProtoReflect.Descriptor instead.
func (*ListDrivesResponse) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{16}
}

func (x *ListDrivesResponse) GetDrives() []*Drive {
	if x != nil {
		return x.Drives
	}
	return nil
}

type GetDriveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"` // serial, WWN, or unambiguous prefix of either
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriveRequest) Reset() {
	*x = GetDriveRequest{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriveRequest) ProtoMessage() {}

func (x *GetDriveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriveRequest.ProtoReflect.Descriptor instead.
func (*GetDriveRequest) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{17}
}

func (x *GetDriveRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type GetDriveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drive         *Drive                 `protobuf:"bytes,1,opt,name=drive,proto3" json:"drive,omitempty"`
	Keys          []string               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`                               // every identity key the drive has been seen under
	LastStatus    *Event                 `protobuf:"bytes,3,opt,name=last_status,json=lastStatus,proto3" json:"last_status,omitempty"` // the status_changed event behind Drive.status, if any
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriveResponse) Reset() {
	*x = GetDriveResponse{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriveResponse) ProtoMessage() {}

func (x *GetDriveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriveResponse.ProtoReflect.Descriptor instead.
func (*GetDriveResponse) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{18}
}

func (x *GetDriveResponse) GetDrive() *Drive {
	if x != nil {
		return x.Drive
	}
	return nil
}

func (x *GetDriveResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *GetDriveResponse) GetLastStatus() *Event {
	if x != nil {
		return x.LastStatus
	}
	return nil
}

type GetDriveHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriveHistoryRequest) Reset() {
	*x = GetDriveHistoryRequest{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriveHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriveHistoryRequest) ProtoMessage() {}

func (x *GetDriveHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriveHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetDriveHistoryRequest) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{19}
}

func (x *GetDriveHistoryRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type GetDriveHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drive         *Drive                 `protobuf:"bytes,1,opt,name=drive,proto3" json:"drive,omitempty"`
	Placements    []*Placement           `protobuf:"bytes,2,rep,name=placements,proto3" json:"placements,omitempty"` // oldest first
	Events        []*Event               `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`         // oldest first
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriveHistoryResponse) Reset() {
	*x = GetDriveHistoryResponse{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriveHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriveHistoryResponse) ProtoMessage() {}

func (x *GetDriveHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriveHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetDriveHistoryResponse) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{20}
}

func (x *GetDriveHistoryResponse) GetDrive() *Drive {
	if x != nil {
		return x.Drive
	}
	return nil
}

func (x *GetDriveHistoryResponse) GetPlacements() []*Placement {
	if x != nil {
		return x.Placements
	}
	return nil
}

func (x *GetDriveHistoryResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=since,proto3" json:"since,omitempty"`
	Kinds         []string               `protobuf:"bytes,2,rep,name=kinds,proto3" json:"kinds,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"` // 0 = server default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{21}
}

func (x *ListEventsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *ListEventsRequest) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *ListEventsRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ListEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{22}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type ListMissingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMissingRequest) Reset() {
	*x = ListMissingRequest{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMissingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMissingRequest) ProtoMessage() {}

func (x *ListMissingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMissingRequest.ProtoReflect.Descriptor instead.
func (*ListMissingRequest) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{23}
}

// Ghost is a pool member a host still expects that matches no present
// device.
type Ghost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Pool          string                 `protobuf:"bytes,2,opt,name=pool,proto3" json:"pool,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Guid          string                 `protobuf:"bytes,4,opt,name=guid,proto3" json:"guid,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Serial        string                 `protobuf:"bytes,6,opt,name=serial,proto3" json:"serial,omitempty"` // when the path resolved to a known drive
	Wwn           string                 `protobuf:"bytes,7,opt,name=wwn,proto3" json:"wwn,omitempty"`
	FirstSeen     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ghost) Reset() {
	*x = Ghost{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ghost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ghost) ProtoMessage() {}

func (x *Ghost) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ghost.ProtoReflect.Descriptor instead.
func (*Ghost) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{24}
}

func (x *Ghost) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Ghost) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *Ghost) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Ghost) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *Ghost) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Ghost) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *Ghost) GetWwn() string {
	if x != nil {
		return x.Wwn
	}
	return ""
}

func (x *Ghost) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *Ghost) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

type ListMissingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drives        []*Drive               `protobuf:"bytes,1,rep,name=drives,proto3" json:"drives,omitempty"` // each with last set
	Ghosts        []*Ghost               `protobuf:"bytes,2,rep,name=ghosts,proto3" json:"ghosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMissingResponse) Reset() {
	*x = ListMissingResponse{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMissingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMissingResponse) ProtoMessage() {}

func (x *ListMissingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMissingResponse.ProtoReflect.Descriptor instead.
func (*ListMissingResponse) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{25}
}

func (x *ListMissingResponse) GetDrives() []*Drive {
	if x != nil {
		return x.Drives
	}
	return nil
}

func (x *ListMissingResponse) GetGhosts() []*Ghost {
	if x != nil {
		return x.Ghosts
	}
	return nil
}

type AnnotateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "" = note only
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotateRequest) Reset() {
	*x = AnnotateRequest{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotateRequest) ProtoMessage() {}

func (x *AnnotateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotateRequest.ProtoReflect.Descriptor instead.
func (*AnnotateRequest) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{26}
}

func (x *AnnotateRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *AnnotateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AnnotateRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *AnnotateRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

type AnnotateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnotateResponse) Reset() {
	*x = AnnotateResponse{}
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnotateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotateResponse) ProtoMessage() {}

func (x *AnnotateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drivelist_v1_drivelist_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotateResponse.ProtoReflect.Descriptor instead.
func (*AnnotateResponse) Descriptor() ([]byte, []int) {
	return file_drivelist_v1_drivelist_proto_rawDescGZIP(), []int{27}
}

func (x *AnnotateResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_drivelist_v1_drivelist_proto protoreflect.FileDescriptor

const file_drivelist_v1_drivelist_proto_rawDesc = "" +
	"\n" +
	"\x1cdrivelist/v1/drivelist.proto\x12\fdrivelist.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"~\n" +
	"\fHostIdentity\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\"g\n" +
	"\rDriveIdentity\x12\x10\n" +
	"\x03wwn\x18\x01 \x01(\tR\x03wwn\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x16\n" +
	"\x06serial\x18\x04 \x01(\tR\x06serial\"\xfc\x02\n" +
	"\x06Device\x12\x19\n" +
	"\bdev_name\x18\x01 \x01(\tR\adevName\x127\n" +
	"\bidentity\x18\x02 \x01(\v2\x1b.drivelist.v1.DriveIdentityR\bidentity\x12#\n" +
	"\x03bus\x18\x03 \x01(\x0e2\x11.drivelist.v1.BusR\x03bus\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x04R\tsizeBytes\x12\x1a\n" +
	"\bexpander\x18\x05 \x01(\tR\bexpander\x12\x10\n" +
	"\x03bay\x18\x06 \x01(\tR\x03bay\x12%\n" +
	"\x0eenclosure_path\x18\a \x01(\tR\renclosurePath\x12\x12\n" +
	"\x04uses\x18\b \x03(\tR\x04uses\x12\x1b\n" +
	"\tdev_links\x18\t \x03(\tR\bdevLinks\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\x12!\n" +
	"\fmember_state\x18\v \x01(\tR\vmemberState\x12\x1b\n" +
	"\tscsi_addr\x18\f \x01(\tR\bscsiAddr\"_\n" +
	"\bEmptyBay\x12\x1a\n" +
	"\bexpander\x18\x01 \x01(\tR\bexpander\x12\x10\n" +
	"\x03bay\x18\x02 \x01(\tR\x03bay\x12%\n" +
	"\x0eenclosure_path\x18\x03 \x01(\tR\renclosurePath\"b\n" +
	"\x0eUnmappedMember\x12\x12\n" +
	"\x04pool\x18\x01 \x01(\tR\x04pool\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04guid\x18\x03 \x01(\tR\x04guid\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\"\xfc\x02\n" +
	"\x16ReportInventoryRequest\x12.\n" +
	"\x04host\x18\x01 \x01(\v2\x1a.drivelist.v1.HostIdentityR\x04host\x12;\n" +
	"\vobserved_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12.\n" +
	"\adevices\x18\x03 \x03(\v2\x14.drivelist.v1.DeviceR\adevices\x125\n" +
	"\n" +
	"empty_bays\x18\x04 \x03(\v2\x16.drivelist.v1.EmptyBayR\temptyBays\x12G\n" +
	"\x10unmapped_members\x18\x05 \x03(\v2\x1c.drivelist.v1.UnmappedMemberR\x0funmappedMembers\x12\x1a\n" +
	"\bcomplete\x18\x06 \x01(\bR\bcomplete\x12)\n" +
	"\x10collector_errors\x18\a \x03(\tR\x0fcollectorErrors\"r\n" +
	"\vDriveStatus\x127\n" +
	"\bidentity\x18\x01 \x01(\v2\x1b.drivelist.v1.DriveIdentityR\bidentity\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\"\x95\x02\n" +
	"\vAgentConfig\x12H\n" +
	"\x12inventory_interval\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x11inventoryInterval\x12@\n" +
	"\x0esmart_interval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\rsmartInterval\x126\n" +
	"\tio_bucket\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bioBucket\x12#\n" +
	"\rcollect_smart\x18\x04 \x01(\bR\fcollectSmart\x12\x1d\n" +
	"\n" +
	"collect_io\x18\x05 \x01(\bR\tcollectIo\"\xde\x01\n" +
	"\x17ReportInventoryResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x02 \x01(\tR\frejectReason\x12\x18\n" +
	"\achanged\x18\x03 \x01(\bR\achanged\x125\n" +
	"\bstatuses\x18\x04 \x03(\v2\x19.drivelist.v1.DriveStatusR\bstatuses\x121\n" +
	"\x06config\x18\x05 \x01(\v2\x19.drivelist.v1.AgentConfigR\x06config\"\x92\x03\n" +
	"\x04Host\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x02 \x01(\tR\tmachineId\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x129\n" +
	"\n" +
	"first_seen\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tfirstSeen\x12;\n" +
	"\vlast_report\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastReport\x12;\n" +
	"\vstale_since\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"staleSince\x12\x1f\n" +
	"\vdrive_count\x18\b \x01(\x05R\n" +
	"driveCount\x12#\n" +
	"\rmissing_count\x18\t \x01(\x05R\fmissingCount\x12\x1f\n" +
	"\vghost_count\x18\n" +
	" \x01(\x05R\n" +
	"ghostCount\"\xce\x02\n" +
	"\tPlacement\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1a\n" +
	"\bexpander\x18\x02 \x01(\tR\bexpander\x12\x10\n" +
	"\x03bay\x18\x03 \x01(\tR\x03bay\x12\x19\n" +
	"\bdev_name\x18\x04 \x01(\tR\adevName\x12\x12\n" +
	"\x04uses\x18\x05 \x03(\tR\x04uses\x129\n" +
	"\n" +
	"first_seen\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tfirstSeen\x127\n" +
	"\tlast_seen\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x125\n" +
	"\bended_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12\x1d\n" +
	"\n" +
	"end_reason\x18\t \x01(\tR\tendReason\"\xcd\x03\n" +
	"\x05Drive\x12\x19\n" +
	"\bdrive_id\x18\x01 \x01(\x03R\adriveId\x12\x10\n" +
	"\x03wwn\x18\x02 \x01(\tR\x03wwn\x12\x16\n" +
	"\x06vendor\x18\x03 \x01(\tR\x06vendor\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x16\n" +
	"\x06serial\x18\x05 \x01(\tR\x06serial\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x04R\tsizeBytes\x12#\n" +
	"\x03bus\x18\a \x01(\x0e2\x11.drivelist.v1.BusR\x03bus\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x129\n" +
	"\n" +
	"first_seen\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tfirstSeen\x127\n" +
	"\tlast_seen\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x121\n" +
	"\acurrent\x18\v \x01(\v2\x17.drivelist.v1.PlacementR\acurrent\x12+\n" +
	"\x04last\x18\f \x01(\v2\x17.drivelist.v1.PlacementR\x04last\x12!\n" +
	"\fmember_state\x18\r \x01(\tR\vmemberState\"\xd8\x01\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12*\n" +
	"\x02ts\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x16\n" +
	"\x06serial\x18\x04 \x01(\tR\x06serial\x12\x10\n" +
	"\x03wwn\x18\x05 \x01(\tR\x03wwn\x12\x1a\n" +
	"\bhostname\x18\x06 \x01(\tR\bhostname\x12\x16\n" +
	"\x06detail\x18\a \x01(\tR\x06detail\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\"\x12\n" +
	"\x10ListHostsRequest\"=\n" +
	"\x11ListHostsResponse\x12(\n" +
	"\x05hosts\x18\x01 \x03(\v2\x12.drivelist.v1.HostR\x05hosts\"\x99\x01\n" +
	"\x11ListDrivesRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x16\n" +
	"\x06status\x18\x02 \x03(\tR\x06status\x12\x1f\n" +
	"\vunused_only\x18\x03 \x01(\bR\n" +
	"unusedOnly\x12!\n" +
	"\fmissing_only\x18\x04 \x01(\bR\vmissingOnly\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\"A\n" +
	"\x12ListDrivesResponse\x12+\n" +
	"\x06drives\x18\x01 \x03(\v2\x13.drivelist.v1.DriveR\x06drives\"#\n" +
	"\x0fGetDriveRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\"\x87\x01\n" +
	"\x10GetDriveResponse\x12)\n" +
	"\x05drive\x18\x01 \x01(\v2\x13.drivelist.v1.DriveR\x05drive\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\tR\x04keys\x124\n" +
	"\vlast_status\x18\x03 \x01(\v2\x13.drivelist.v1.EventR\n" +
	"lastStatus\"*\n" +
	"\x16GetDriveHistoryRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\"\xaa\x01\n" +
	"\x17GetDriveHistoryResponse\x12)\n" +
	"\x05drive\x18\x01 \x01(\v2\x13.drivelist.v1.DriveR\x05drive\x127\n" +
	"\n" +
	"placements\x18\x02 \x03(\v2\x17.drivelist.v1.PlacementR\n" +
	"placements\x12+\n" +
	"\x06events\x18\x03 \x03(\v2\x13.drivelist.v1.EventR\x06events\"\x85\x01\n" +
	"\x11ListEventsRequest\x120\n" +
	"\x05since\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12\x14\n" +
	"\x05kinds\x18\x02 \x03(\tR\x05kinds\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"A\n" +
	"\x12ListEventsResponse\x12+\n" +
	"\x06events\x18\x01 \x03(\v2\x13.drivelist.v1.EventR\x06events\"\x14\n" +
	"\x12ListMissingRequest\"\x93\x02\n" +
	"\x05Ghost\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04pool\x18\x02 \x01(\tR\x04pool\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04guid\x18\x04 \x01(\tR\x04guid\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x16\n" +
	"\x06serial\x18\x06 \x01(\tR\x06serial\x12\x10\n" +
	"\x03wwn\x18\a \x01(\tR\x03wwn\x129\n" +
	"\n" +
	"first_seen\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tfirstSeen\x127\n" +
	"\tlast_seen\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\"o\n" +
	"\x13ListMissingResponse\x12+\n" +
	"\x06drives\x18\x01 \x03(\v2\x13.drivelist.v1.DriveR\x06drives\x12+\n" +
	"\x06ghosts\x18\x02 \x03(\v2\x13.drivelist.v1.GhostR\x06ghosts\"e\n" +
	"\x0fAnnotateRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\"=\n" +
	"\x10AnnotateResponse\x12)\n" +
	"\x05event\x18\x01 \x01(\v2\x13.drivelist.v1.EventR\x05event*`\n" +
	"\x03Bus\x12\x13\n" +
	"\x0fBUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aBUS_SAS\x10\x01\x12\f\n" +
	"\bBUS_SATA\x10\x02\x12\f\n" +
	"\bBUS_NVME\x10\x03\x12\v\n" +
	"\aBUS_USB\x10\x04\x12\x0e\n" +
	"\n" +
	"BUS_VIRTIO\x10\x052k\n" +
	"\tCollector\x12^\n" +
	"\x0fReportInventory\x12$.drivelist.v1.ReportInventoryRequest\x1a%.drivelist.v1.ReportInventoryResponse2\xc1\x04\n" +
	"\x05Query\x12L\n" +
	"\tListHosts\x12\x1e.drivelist.v1.ListHostsRequest\x1a\x1f.drivelist.v1.ListHostsResponse\x12O\n" +
	"\n" +
	"ListDrives\x12\x1f.drivelist.v1.ListDrivesRequest\x1a .drivelist.v1.ListDrivesResponse\x12I\n" +
	"\bGetDrive\x12\x1d.drivelist.v1.GetDriveRequest\x1a\x1e.drivelist.v1.GetDriveResponse\x12^\n" +
	"\x0fGetDriveHistory\x12$.drivelist.v1.GetDriveHistoryRequest\x1a%.drivelist.v1.GetDriveHistoryResponse\x12O\n" +
	"\n" +
	"ListEvents\x12\x1f.drivelist.v1.ListEventsRequest\x1a .drivelist.v1.ListEventsResponse\x12R\n" +
	"\vListMissing\x12 .drivelist.v1.ListMissingRequest\x1a!.drivelist.v1.ListMissingResponse\x12I\n" +
	"\bAnnotate\x12\x1d.drivelist.v1.AnnotateRequest\x1a\x1e.drivelist.v1.AnnotateResponseBEZCgithub.com/scottlaird/drivelist/internal/pb/drivelistv1;drivelistv1b\x06proto3"

var (
	file_drivelist_v1_drivelist_proto_rawDescOnce sync.Once
	file_drivelist_v1_drivelist_proto_rawDescData []byte
)

func file_drivelist_v1_drivelist_proto_rawDescGZIP() []byte {
	file_drivelist_v1_drivelist_proto_rawDescOnce.Do(func() {
		file_drivelist_v1_drivelist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_drivelist_v1_drivelist_proto_rawDesc), len(file_drivelist_v1_drivelist_proto_rawDesc)))
	})
	return file_drivelist_v1_drivelist_proto_rawDescData
}

var file_drivelist_v1_drivelist_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_drivelist_v1_drivelist_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_drivelist_v1_drivelist_proto_goTypes = []any{
	(Bus)(0),                        // 0: drivelist.v1.Bus
	(*HostIdentity)(nil),            // 1: drivelist.v1.HostIdentity
	(*DriveIdentity)(nil),           // 2: drivelist.v1.DriveIdentity
	(*Device)(nil),                  // 3: drivelist.v1.Device
	(*EmptyBay)(nil),                // 4: drivelist.v1.EmptyBay
	(*UnmappedMember)(nil),          // 5: drivelist.v1.UnmappedMember
	(*ReportInventoryRequest)(nil),  // 6: drivelist.v1.ReportInventoryRequest
	(*DriveStatus)(nil),             // 7: drivelist.v1.DriveStatus
	(*AgentConfig)(nil),             // 8: drivelist.v1.AgentConfig
	(*ReportInventoryResponse)(nil), // 9: drivelist.v1.ReportInventoryResponse
	(*Host)(nil),                    // 10: drivelist.v1.Host
	(*Placement)(nil),               // 11: drivelist.v1.Placement
	(*Drive)(nil),                   // 12: drivelist.v1.Drive
	(*Event)(nil),                   // 13: drivelist.v1.Event
	(*ListHostsRequest)(nil),        // 14: drivelist.v1.ListHostsRequest
	(*ListHostsResponse)(nil),       // 15: drivelist.v1.ListHostsResponse
	(*ListDrivesRequest)(nil),       // 16: drivelist.v1.ListDrivesRequest
	(*ListDrivesResponse)(nil),      // 17: drivelist.v1.ListDrivesResponse
	(*GetDriveRequest)(nil),         // 18: drivelist.v1.GetDriveRequest
	(*GetDriveResponse)(nil),        // 19: drivelist.v1.GetDriveResponse
	(*GetDriveHistoryRequest)(nil),  // 20: drivelist.v1.GetDriveHistoryRequest
	(*GetDriveHistoryResponse)(nil), // 21: drivelist.v1.GetDriveHistoryResponse
	(*ListEventsRequest)(nil),       // 22: drivelist.v1.ListEventsRequest
	(*ListEventsResponse)(nil),      // 23: drivelist.v1.ListEventsResponse
	(*ListMissingRequest)(nil),      // 24: drivelist.v1.ListMissingRequest
	(*Ghost)(nil),                   // 25: drivelist.v1.Ghost
	(*ListMissingResponse)(nil),     // 26: drivelist.v1.ListMissingResponse
	(*AnnotateRequest)(nil),         // 27: drivelist.v1.AnnotateRequest
	(*AnnotateResponse)(nil),        // 28: drivelist.v1.AnnotateResponse
	(*timestamppb.Timestamp)(nil),   // 29: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),     // 30: google.protobuf.Duration
}
var file_drivelist_v1_drivelist_proto_depIdxs = []int32{
	2,  // 0: drivelist.v1.Device.identity:type_name -> drivelist.v1.DriveIdentity
	0,  // 1: drivelist.v1.Device.bus:type_name -> drivelist.v1.Bus
	1,  // 2: drivelist.v1.ReportInventoryRequest.host:type_name -> drivelist.v1.HostIdentity
	29, // 3: drivelist.v1.ReportInventoryRequest.observed_at:type_name -> google.protobuf.Timestamp
	3,  // 4: drivelist.v1.ReportInventoryRequest.devices:type_name -> drivelist.v1.Device
	4,  // 5: drivelist.v1.ReportInventoryRequest.empty_bays:type_name -> drivelist.v1.EmptyBay
	5,  // 6: drivelist.v1.ReportInventoryRequest.unmapped_members:type_name -> drivelist.v1.UnmappedMember
	2,  // 7: drivelist.v1.DriveStatus.identity:type_name -> drivelist.v1.DriveIdentity
	30, // 8: drivelist.v1.AgentConfig.inventory_interval:type_name -> google.protobuf.Duration
	30, // 9: drivelist.v1.AgentConfig.smart_interval:type_name -> google.protobuf.Duration
	30, // 10: drivelist.v1.AgentConfig.io_bucket:type_name -> google.protobuf.Duration
	7,  // 11: drivelist.v1.ReportInventoryResponse.statuses:type_name -> drivelist.v1.DriveStatus
	8,  // 12: drivelist.v1.ReportInventoryResponse.config:type_name -> drivelist.v1.AgentConfig
	29, // 13: drivelist.v1.Host.first_seen:type_name -> google.protobuf.Timestamp
	29, // 14: drivelist.v1.Host.last_report:type_name -> google.protobuf.Timestamp
	29, // 15: drivelist.v1.Host.stale_since:type_name -> google.protobuf.Timestamp
	29, // 16: drivelist.v1.Placement.first_seen:type_name -> google.protobuf.Timestamp
	29, // 17: drivelist.v1.Placement.last_seen:type_name -> google.protobuf.Timestamp
	29, // 18: drivelist.v1.Placement.ended_at:type_name -> google.protobuf.Timestamp
	0,  // 19: drivelist.v1.Drive.bus:type_name -> drivelist.v1.Bus
	29, // 20: drivelist.v1.Drive.first_seen:type_name -> google.protobuf.Timestamp
	29, // 21: drivelist.v1.Drive.last_seen:type_name -> google.protobuf.Timestamp
	11, // 22: drivelist.v1.Drive.current:type_name -> drivelist.v1.Placement
	11, // 23: drivelist.v1.Drive.last:type_name -> drivelist.v1.Placement
	29, // 24: drivelist.v1.Event.ts:type_name -> google.protobuf.Timestamp
	10, // 25: drivelist.v1.ListHostsResponse.hosts:type_name -> drivelist.v1.Host
	12, // 26: drivelist.v1.ListDrivesResponse.drives:type_name -> drivelist.v1.Drive
	12, // 27: drivelist.v1.GetDriveResponse.drive:type_name -> drivelist.v1.Drive
	13, // 28: drivelist.v1.GetDriveResponse.last_status:type_name -> drivelist.v1.Event
	12, // 29: drivelist.v1.GetDriveHistoryResponse.drive:type_name -> drivelist.v1.Drive
	11, // 30: drivelist.v1.GetDriveHistoryResponse.placements:type_name -> drivelist.v1.Placement
	13, // 31: drivelist.v1.GetDriveHistoryResponse.events:type_name -> drivelist.v1.Event
	29, // 32: drivelist.v1.ListEventsRequest.since:type_name -> google.protobuf.Timestamp
	13, // 33: drivelist.v1.ListEventsResponse.events:type_name -> drivelist.v1.Event
	29, // 34: drivelist.v1.Ghost.first_seen:type_name -> google.protobuf.Timestamp
	29, // 35: drivelist.v1.Ghost.last_seen:type_name -> google.protobuf.Timestamp
	12, // 36: drivelist.v1.ListMissingResponse.drives:type_name -> drivelist.v1.Drive
	25, // 37: drivelist.v1.ListMissingResponse.ghosts:type_name -> drivelist.v1.Ghost
	13, // 38: drivelist.v1.AnnotateResponse.event:type_name -> drivelist.v1.Event
	6,  // 39: drivelist.v1.Collector.ReportInventory:input_type -> drivelist.v1.ReportInventoryRequest
	14, // 40: drivelist.v1.Query.ListHosts:input_type -> drivelist.v1.ListHostsRequest
	16, // 41: drivelist.v1.Query.ListDrives:input_type -> drivelist.v1.ListDrivesRequest
	18, // 42: drivelist.v1.Query.GetDrive:input_type -> drivelist.v1.GetDriveRequest
	20, // 43: drivelist.v1.Query.GetDriveHistory:input_type -> drivelist.v1.GetDriveHistoryRequest
	22, // 44: drivelist.v1.Query.ListEvents:input_type -> drivelist.v1.ListEventsRequest
	24, // 45: drivelist.v1.Query.ListMissing:input_type -> drivelist.v1.ListMissingRequest
	27, // 46: drivelist.v1.Query.Annotate:input_type -> drivelist.v1.AnnotateRequest
	9,  // 47: drivelist.v1.Collector.ReportInventory:output_type -> drivelist.v1.ReportInventoryResponse
	15, // 48: drivelist.v1.Query.ListHosts:output_type -> drivelist.v1.ListHostsResponse
	17, // 49: drivelist.v1.Query.ListDrives:output_type -> drivelist.v1.ListDrivesResponse
	19, // 50: drivelist.v1.Query.GetDrive:output_type -> drivelist.v1.GetDriveResponse
	21, // 51: drivelist.v1.Query.GetDriveHistory:output_type -> drivelist.v1.GetDriveHistoryResponse
	23, // 52: drivelist.v1.Query.ListEvents:output_type -> drivelist.v1.ListEventsResponse
	26, // 53: drivelist.v1.Query.ListMissing:output_type -> drivelist.v1.ListMissingResponse
	28, // 54: drivelist.v1.Query.Annotate:output_type -> drivelist.v1.AnnotateResponse
	47, // [47:55] is the sub-list for method output_type
	39, // [39:47] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_drivelist_v1_drivelist_proto_init() }
func file_drivelist_v1_drivelist_proto_init() {
	if File_drivelist_v1_drivelist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_drivelist_v1_drivelist_proto_rawDesc), len(file_drivelist_v1_drivelist_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_drivelist_v1_drivelist_proto_goTypes,
		DependencyIndexes: file_drivelist_v1_drivelist_proto_depIdxs,
		EnumInfos:         file_drivelist_v1_drivelist_proto_enumTypes,
		MessageInfos:      file_drivelist_v1_drivelist_proto_msgTypes,
	}.Build()
	File_drivelist_v1_drivelist_proto = out.File
	file_drivelist_v1_drivelist_proto_goTypes = nil
	file_drivelist_v1_drivelist_proto_depIdxs = nil
}
